/**
 * Variable registry. Visualizers read this; they do not invent meanings.
 */
export const VARIABLES = {
  Eg: {
    id: 'Eg', symbol: 'E_g', name: 'bandgap', units: 'eV',
    meaning: 'Minimum energy to promote an electron from the valence band to the conduction band.',
    determinedBy: ['material', 'T (weakly)'],
    affects: ['lg', 'ni', 'absorption', 'n', 'p', 'sigma'],
    role: 'looked up',
    visual: 'vertical gap between Ec and Ev',
    ifUp: 'Harder optical and thermal excitation. λg shorter. ni drops exponentially.',
    ifDown: 'Easier pair generation and longer-wavelength absorption.',
  },
  EC: {
    id: 'EC', symbol: 'E_c', name: 'conduction-band edge', units: 'eV',
    meaning: 'Lowest electron energy in the conduction band.',
    determinedBy: ['Eg', 'Ev reference'],
    affects: ['n', 'f'],
    role: 'reference',
    visual: 'top band edge',
    ifUp: 'EC−EF grows, n falls.',
    ifDown: 'EC approaches EF, n rises.',
  },
  EV: {
    id: 'EV', symbol: 'E_v', name: 'valence-band edge', units: 'eV',
    meaning: 'Highest electron energy in the valence band. Holes live just below it.',
    determinedBy: ['band structure'],
    affects: ['p'],
    role: 'reference',
    visual: 'bottom band edge',
    ifUp: 'EF−EV shrinks, p rises.',
    ifDown: 'Holes become rarer.',
  },
  Ei: {
    id: 'Ei', symbol: 'E_i', name: 'intrinsic Fermi level', units: 'eV',
    meaning: 'The EF that an undoped crystal would have. Near midgap.',
    determinedBy: ['Eg', 'NC/NV'],
    affects: ['n', 'p'],
    role: 'calculated',
    visual: 'dashed line near midgap',
    ifUp: 'Reference for n and p shifts.',
    ifDown: 'Same, opposite sign.',
  },
  EF: {
    id: 'EF', symbol: 'E_F', name: 'Fermi level', units: 'eV',
    meaning: 'Chemical-potential-like energy that sets occupation. Not a pile of electrons.',
    determinedBy: ['NA', 'ND', 'T', 'ni'],
    affects: ['n', 'p', 'f'],
    role: 'calculated',
    visual: 'amber dashed line',
    ifUp: 'n rises exponentially, p falls, f(E) slides up.',
    ifDown: 'p rises, n falls.',
  },
  E: {
    id: 'E', symbol: 'E', name: 'energy', units: 'eV',
    meaning: 'Electron energy of a state, or energy of a photon.',
    determinedBy: ['context'],
    affects: ['f'],
    role: 'given or scanned',
    visual: 'vertical axis',
    ifUp: 'Occupation of that state drops if it is above EF.',
    ifDown: 'Occupation rises.',
  },
  lambda: {
    id: 'lambda', symbol: '\\lambda', name: 'wavelength', units: 'nm',
    meaning: 'Distance between wave crests. Inverse to photon frequency and energy.',
    determinedBy: ['source'],
    affects: ['Eph', 'absorption'],
    role: 'given',
    visual: 'photon wave',
    ifUp: 'Ephoton falls. May drop below Eg and stop absorbing.',
    ifDown: 'Ephoton rises.',
  },
  lg: {
    id: 'lg', symbol: '\\lambda_g', name: 'gap wavelength', units: 'nm',
    meaning: 'Longest wavelength a photon can have and still pay Eg.',
    determinedBy: ['Eg'],
    affects: ['absorption'],
    role: 'calculated',
    visual: 'mark on the spectrum',
    ifUp: 'Material absorbs farther into the red / IR.',
    ifDown: 'Absorption edge moves blue.',
  },
  f: {
    id: 'f', symbol: 'f(E)', name: 'Fermi–Dirac occupancy', units: '1',
    meaning: 'Probability that an available state at energy E is occupied.',
    determinedBy: ['E', 'EF', 'T'],
    affects: ['n', 'p'],
    role: 'calculated',
    visual: 'occupancy curve',
    ifUp: 'That energy is more likely filled. Not the same as “more electrons exist.”',
    ifDown: 'That state is emptier.',
  },
  T: {
    id: 'T', symbol: 'T', name: 'temperature', units: 'K',
    meaning: 'Thermal energy scale. Sets kT, ni, ionization, and the smear of f(E).',
    determinedBy: ['environment'],
    affects: ['kT', 'ni', 'f', 'n', 'p', 'sigma', 'ionization'],
    role: 'given',
    visual: 'thermal smear',
    ifUp: 'kT grows, ni grows, f(E) smears, freeze-out lifts.',
    ifDown: 'Exponentials freeze. Carriers can vanish even if dopants exist.',
  },
  k: {
    id: 'k', symbol: 'k', name: 'Boltzmann constant', units: 'eV/K',
    meaning: 'Converts temperature into an energy. kT is the thermal yardstick.',
    determinedBy: ['constant'],
    affects: ['all exponentials'],
    role: 'looked up',
    visual: 'kT bracket',
    ifUp: 'Thermally accessible window widens.',
    ifDown: 'Exponentials become harsher.',
  },
  n: {
    id: 'n', symbol: 'n', name: 'electron concentration', units: 'cm^{-3}',
    meaning: 'Conduction-band electrons per unit volume.',
    determinedBy: ['EF', 'ni', 'T', 'ND', 'NA'],
    affects: ['sigma', 'p via mass action'],
    role: 'calculated',
    visual: 'cyan dots in CB',
    ifUp: 'Electron current rises. At equilibrium p falls.',
    ifDown: 'Electrons rarer.',
  },
  p: {
    id: 'p', symbol: 'p', name: 'hole concentration', units: 'cm^{-3}',
    meaning: 'Empty valence-band states that behave as +q carriers.',
    determinedBy: ['EF', 'ni', 'T', 'NA', 'ND'],
    affects: ['sigma', 'n via mass action'],
    role: 'calculated',
    visual: 'open crimson circles in VB',
    ifUp: 'Hole current rises. At equilibrium n falls.',
    ifDown: 'Holes rarer.',
  },
  ni: {
    id: 'ni', symbol: 'n_i', name: 'intrinsic concentration', units: 'cm^{-3}',
    meaning: 'n and p of the undoped crystal. Also the equilibrium scale: np = ni².',
    determinedBy: ['Eg', 'T', 'NC', 'NV'],
    affects: ['n', 'p', 'sigma', 'EF placement'],
    role: 'looked up / modelled',
    visual: 'pair-generation rate',
    ifUp: 'More thermal pairs. Doping owns n,p less.',
    ifDown: 'Doping dominates more easily.',
  },
  NA: {
    id: 'NA', symbol: 'N_A', name: 'acceptor density', units: 'cm^{-3}',
    meaning: 'Ionizable impurities that want an electron and leave a hole in the valence band.',
    determinedBy: ['processing'],
    affects: ['EF', 'p', 'n'],
    role: 'given',
    visual: 'fixed A− ions',
    ifUp: 'EF drops toward Ev. p rises (if ionized).',
    ifDown: 'Less p-type.',
  },
  ND: {
    id: 'ND', symbol: 'N_D', name: 'donor density', units: 'cm^{-3}',
    meaning: 'Ionizable impurities that give an electron to the conduction band.',
    determinedBy: ['processing'],
    affects: ['EF', 'n', 'p'],
    role: 'given',
    visual: 'fixed D+ ions',
    ifUp: 'EF rises toward Ec. n rises (if ionized).',
    ifDown: 'Less n-type.',
  },
  mun: {
    id: 'mun', symbol: '\\mu_n', name: 'electron mobility', units: 'cm^{2}/V·s',
    meaning: 'How fast an electron drifts per unit field. Lattice + impurity scattering set it.',
    determinedBy: ['material', 'T', 'doping'],
    affects: ['sigma', 'Jn'],
    role: 'looked up',
    visual: 'electron drift speed',
    ifUp: 'Same n carries more current.',
    ifDown: 'Electrons slog.',
  },
  mup: {
    id: 'mup', symbol: '\\mu_p', name: 'hole mobility', units: 'cm^{2}/V·s',
    meaning: 'Hole drift per unit field. Usually smaller than μn.',
    determinedBy: ['material', 'T', 'doping'],
    affects: ['sigma', 'Jp'],
    role: 'looked up',
    visual: 'hole drift speed',
    ifUp: 'Same p carries more current.',
    ifDown: 'Holes slog.',
  },
  sigma: {
    id: 'sigma', symbol: '\\sigma', name: 'conductivity', units: 'S/cm',
    meaning: 'How much current density you get per electric field. J = σE.',
    determinedBy: ['n', 'p', 'mun', 'mup', 'q'],
    affects: ['rho', 'J'],
    role: 'calculated',
    visual: 'easy current',
    ifUp: 'Resistivity falls. Same E makes more J.',
    ifDown: 'The crystal looks more insulating.',
  },
  rho: {
    id: 'rho', symbol: '\\rho', name: 'resistivity', units: '\\Omega·cm',
    meaning: 'The inverse language of conductivity. E = ρJ.',
    determinedBy: ['sigma'],
    affects: ['resistance'],
    role: 'calculated',
    visual: 'hard current',
    ifUp: 'You need more field for the same J.',
    ifDown: 'The wafer conducts easily.',
  },
  q: {
    id: 'q', symbol: 'q', name: 'elementary charge', units: 'C',
    meaning: 'Charge of one electron or hole. Converts a count of carriers into coulombs.',
    determinedBy: ['constant'],
    affects: ['sigma', 'J'],
    role: 'looked up',
    visual: 'charge on each carrier',
    ifUp: 'Each carrier carries more charge (not a real knob).',
    ifDown: '—',
  },
  alpha: {
    id: 'alpha', symbol: '\\alpha', name: 'absorption coefficient', units: 'cm^{-1}',
    meaning: 'How fast intensity dies as light travels. Large α: the wafer eats the beam quickly.',
    determinedBy: ['Ephoton vs Eg', 'gap type'],
    affects: ['transmitted color'],
    role: 'sketched / measured',
    visual: 'α(λ) curve',
    ifUp: 'Photon dies closer to the surface.',
    ifDown: 'Crystal is more transparent.',
  },
  NC: {
    id: 'NC', symbol: 'N_C', name: 'effective CB DOS', units: 'cm^{-3}',
    meaning: 'Equivalent number of conduction states, piled at Ec. Grows as T^{3/2}.',
    determinedBy: ['m*_n', 'T'],
    affects: ['n', 'ni'],
    role: 'looked up',
    visual: 'CB state pile',
    ifUp: 'More room for electrons at the same EF.',
    ifDown: 'Fewer electrons for the same EF.',
  },
  NV: {
    id: 'NV', symbol: 'N_V', name: 'effective VB DOS', units: 'cm^{-3}',
    meaning: 'Equivalent valence states piled at Ev.',
    determinedBy: ['m*_p', 'T'],
    affects: ['p', 'ni'],
    role: 'looked up',
    visual: 'VB state pile',
    ifUp: 'More room for holes.',
    ifDown: 'Fewer holes.',
  },
  Eph: {
    id: 'Eph', symbol: 'E_{\\mathrm{photon}}', name: 'photon energy', units: 'eV',
    meaning: 'Energy of one photon. E = hf = hc/λ.',
    determinedBy: ['lambda'],
    affects: ['absorption'],
    role: 'calculated',
    visual: 'photon',
    ifUp: 'More likely to exceed Eg.',
    ifDown: 'May pass through.',
  },
  freq: {
    id: 'freq', symbol: 'f', name: 'frequency', units: 'Hz',
    meaning: 'Oscillations per second. f = c/λ.',
    determinedBy: ['lambda'],
    affects: ['Eph'],
    role: 'calculated',
    visual: 'wave peaks per time',
    ifUp: 'Each photon is more energetic.',
    ifDown: 'Softer photons.',
  },
  vd: {
    id: 'vd', symbol: 'v_d', name: 'drift velocity', units: 'cm/s',
    meaning: 'Average extra velocity a carrier gains from a field. vd = μE.',
    determinedBy: ['mu', 'Efield'],
    affects: ['J'],
    role: 'calculated',
    visual: 'drift arrows',
    ifUp: 'Each carrier crosses a plane faster.',
    ifDown: 'Slower current.',
  },
  Efield: {
    id: 'Efield', symbol: '\\mathcal{E}', name: 'electric field', units: 'V/cm',
    meaning: 'Force per unit charge. Not the Fermi energy.',
    determinedBy: ['bias', 'geometry'],
    affects: ['vd', 'J'],
    role: 'given',
    visual: 'field arrow',
    ifUp: 'Faster drift, larger J.',
    ifDown: 'Quieter current.',
  },
  J: {
    id: 'J', symbol: 'J', name: 'current density', units: 'A/cm^{2}',
    meaning: 'Charge per time per area. J = σE.',
    determinedBy: ['sigma', 'Efield'],
    affects: ['circuit'],
    role: 'calculated',
    visual: 'conventional current',
    ifUp: 'More amps through the same slice.',
    ifDown: 'Weaker current.',
  },
};

export function variable(id) {
  return VARIABLES[id];
}
