/**
 * Conceptual Exam 1 question bank.
 * Every item has a verified answer and a diagnosis tag.
 */

import { WRITTEN } from './written.js';

export const CATS = [
  { id: 'crystal', label: 'Crystal structures & Miller indices' },
  { id: 'miller', label: 'Crystal structures & Miller indices' },
  { id: 'band', label: 'Band structure' },
  { id: 'photon', label: 'Photon/bandgap physics' },
  { id: 'fermi', label: 'Fermi–Dirac' },
  { id: 'doping', label: 'Doping & impurity physics' },
  { id: 'carriers', label: 'Carrier concentration' },
  { id: 'transport', label: 'Transport' },
  { id: 'temperature', label: 'Temperature dependence' },
  { id: 'pn', label: 'PN-junction physics' },
  { id: 'optics', label: 'Photon/bandgap physics' },
  { id: 'equations', label: 'Equation relationships' },
];

export const DIAG = {
  fd_meaning: 'You can write f(E) but are missing that it is a probability, not a count.',
  ef_move: 'You name n-type correctly but are inconsistent about how EF moves.',
  lam_dir: 'You know E = hc/λ but reverse the wavelength–bandgap direction.',
  w_dop: 'You know the W formula but miss why extra doping narrows depletion.',
  n_alone: 'You treat N (atoms/cell) as density by itself.',
  miller0: 'You treat index 0 as “hits the origin” instead of “parallel.”',
  maj_both: 'You applied n = ND and p = NA in the same crystal.',
  regime: 'You skipped naming freeze-out / extrinsic / intrinsic before predicting n(T).',
  beer: 'You treated an exponential as linear.',
  ionize: 'You skipped T → kT → ionization → carriers.',
  inject: 'You used equilibrium mass action inside an injecting junction.',
  gap_k: 'You forgot that a photon is almost vertical in k-space.',
};

const Q = (row) => row;

const OBJECTIVE = [
  Q({
    id: 'c-sc-n', cat: 'crystal', type: 'mc',
    prompt: 'A simple-cubic conventional cell has an atom at every corner and nowhere else. How many atoms does this cell own?',
    choices: [
      { id: 'a', text: '8, because you can count 8 spheres' },
      { id: 'b', text: '1, because each corner is shared by 8 cells' },
      { id: 'c', text: '1/8, because only one corner is “real”' },
      { id: 'd', text: '2, like BCC without the body atom' },
    ],
    correct: 'b',
    why: '8 corners × 1/8 = 1. The other 7/8 of each corner belong to neighboring cells.',
    whyWrong: {
      a: 'Counting spheres you see is not ownership.',
      c: 'The cell owns 1/8 of each of 8 corners, total 1.',
      d: 'BCC is 2 only after you add the unshared body atom.',
    },
    equation: 'N_{SC}=8\\times 1/8=1', intuition: 'Cuts make the missing 7/8 visible.',
    hw: 'HW1 Q1', module: 'latticelab_homeworks.html?hw=hw1#cell', diagnosis: DIAG.n_alone,
  }),
  Q({
    id: 'c-fcc-n', cat: 'crystal', type: 'mc',
    prompt: 'Why does an FCC conventional cell own 4 atoms, not 14?',
    choices: [
      { id: 'a', text: '8 corners × 1/8 + 6 faces × 1/2 = 4' },
      { id: 'b', text: 'There are only 4 atoms drawn in a “primitive” picture' },
      { id: 'c', text: 'Face atoms are not shared' },
      { id: 'd', text: 'FCC is two SC cells stacked' },
    ],
    correct: 'a',
    why: 'Corners are 8-way shared. Face atoms are 2-way shared. 1 + 3 = 4.',
    whyWrong: {
      b: 'HW1 asks you to count the conventional cell.',
      c: 'Each face atom is shared with one neighbor.',
      d: 'That is not the FCC construction.',
    },
    equation: 'N_{FCC}=4', intuition: 'Turn on fractional cuts and watch the faces split.',
    hw: 'HW1 Q1', module: 'latticelab_homeworks.html?hw=hw1#cell', diagnosis: DIAG.n_alone,
  }),
  Q({
    id: 'c-diamond-n', cat: 'crystal', type: 'mc',
    prompt: 'Silicon’s conventional diamond cell owns 8 atoms. Where do the extra 4 (beyond FCC) live?',
    choices: [
      { id: 'a', text: 'On the faces, owned 1/2 each' },
      { id: 'b', text: 'Entirely inside the cell, on the second FCC sublattice (a/4 shift)' },
      { id: 'c', text: 'At the body center' },
      { id: 'd', text: 'They are shared corners counted twice' },
    ],
    correct: 'b',
    why: 'Diamond is two interpenetrating FCC lattices. The four internals are wholly owned.',
    whyWrong: {
      a: 'Face atoms were already in the FCC 4.',
      c: 'Body center is BCC’s extra atom, not diamond’s.',
      d: 'Double-counting corners would be a mistake, not the structure.',
    },
    equation: 'N_{diamond}=8', intuition: 'Toggle Diamond and look for the internals.',
    hw: 'HW1 Q1', module: 'latticelab_homeworks.html?hw=hw1#cell', diagnosis: DIAG.n_alone,
  }),
  Q({
    id: 'c-n-not-rho', cat: 'crystal', type: 'tf',
    prompt: 'True or false: A crystal with more atoms per conventional cell always has a larger mass density than one with fewer atoms per cell.',
    choices: [{ id: 't', text: 'True' }, { id: 'f', text: 'False' }],
    correct: 'f',
    why: 'Density uses N, molar mass, and a³. A larger N with a much larger a can be lighter. Never rank density from N alone.',
    whyWrong: { t: 'You treated N as density. The denominator a³ can win.' },
    equation: '\\rho \\propto N m / a^3', intuition: 'Si has N=8 but a 5.43 Å cube.',
    hw: 'HW1 Q1, Q3', module: 'latticelab_homeworks.html?hw=hw1#ek', diagnosis: DIAG.n_alone,
  }),
  Q({
    id: 'c-si-n', cat: 'crystal', type: 'mc',
    prompt: 'Atomic number density is n = N / a³. If you stretch a (same N), what happens to n?',
    choices: [
      { id: 'a', text: 'n rises because the cell is “bigger”' },
      { id: 'b', text: 'n falls as 1/a³' },
      { id: 'c', text: 'n is unchanged because N is unchanged' },
      { id: 'd', text: 'n falls as 1/a' },
    ],
    correct: 'b',
    why: 'Same ownership, larger volume.',
    whyWrong: {
      a: 'Bigger cell is more volume, fewer atoms per cm³.',
      c: 'N is per cell, not per cm³.',
      d: 'Volume is a³, not a.',
    },
    equation: 'n=N/a^3', intuition: 'Drag a on the Si calculator.',
    hw: 'HW1 Q3', module: 'latticelab_homeworks.html?hw=hw1#ek', diagnosis: DIAG.n_alone,
  }),
  Q({
    id: 'm-zero-l', cat: 'miller', type: 'mc',
    prompt: 'A plane is parallel to the z-axis. What must l be in (hkl), and why?',
    choices: [
      { id: 'a', text: 'l = 0, because the intercept on z is at infinity' },
      { id: 'b', text: 'l = 0, because the plane hits z at the origin' },
      { id: 'c', text: 'l = 1, because it must cut z once' },
      { id: 'd', text: 'l is undefined for a parallel plane' },
    ],
    correct: 'a',
    why: 'Reciprocal intercept: 1/∞ = 0. The plane never hits z.',
    whyWrong: {
      b: 'Hitting the origin is not what 0 means.',
      c: 'If it cut z at c, l would be finite.',
      d: 'Parallel planes are everyday Miller planes: (110), (100).',
    },
    equation: 'l = c / \\text{intercept}_z', intuition: 'Draw (110) and watch it miss z.',
    hw: 'HW1 Q2', module: 'latticelab_homeworks.html?hw=hw1#miller', diagnosis: DIAG.miller0,
  }),
  Q({
    id: 'm-bar', cat: 'miller', type: 'tf',
    prompt: 'True or false: A negative (barred) Miller index means the plane has a negative area.',
    choices: [{ id: 't', text: 'True' }, { id: 'f', text: 'False' }],
    correct: 'f',
    why: 'A bar means the intercept or direction component is on the negative side of the origin. Size stays positive. We shift the drawing so it still cuts the cube.',
    whyWrong: { t: 'Indices are orientation, not signed area.' },
    equation: '(1\\bar{1}0)', intuition: 'Try (1-10) in the sketcher.',
    hw: 'HW1 Q2', module: 'latticelab_homeworks.html?hw=hw1#miller', diagnosis: DIAG.miller0,
  }),
  Q({
    id: 'm-dir-neg', cat: 'miller', type: 'mc',
    prompt: 'You must draw [01-2] inside the conventional cube. Why does the arrow’s tail often start at z = 1 rather than the origin?',
    choices: [
      { id: 'a', text: 'Negative w shifts the tail by one lattice step so the whole arrow stays in the box' },
      { id: 'b', text: 'The direction changed to [012]' },
      { id: 'c', text: 'Miller directions cannot have negative components' },
      { id: 'd', text: 'z = 1 is required because |w| = 2' },
    ],
    correct: 'a',
    why: 'The crystallographic direction is unchanged. Only the drawing origin moved. |w| > 1 may also scale the shaft so it fits.',
    whyWrong: {
      b: 'Shifting the tail does not flip the index.',
      c: 'HW1 asks for negative components.',
      d: '|w|=2 scales length; the z=1 shift is from the minus sign.',
    },
    equation: '[uvw]', intuition: 'Use the [01-2] preset.',
    hw: 'HW1 Q2', module: 'latticelab_homeworks.html?hw=hw1#miller', diagnosis: DIAG.miller0,
  }),
  Q({
    id: 'm-from-ints', cat: 'miller', type: 'mc',
    prompt: 'A plane intercepts x at a, y at a/2, and never hits z. What are (hkl)?',
    choices: [
      { id: 'a', text: '(120)' },
      { id: 'b', text: '(210)' },
      { id: 'c', text: '(012)' },
      { id: 'd', text: '(201)' },
    ],
    correct: 'a',
    why: 'h = a/a = 1, k = a/(a/2) = 2, l = 0. So (120). (210) swaps the intercepts.',
    whyWrong: {
      b: '(210) cuts x at a/2 and y at a — the swap.',
      c: '(012) is parallel to x, not to z.',
      d: '(201) cuts z.',
    },
    equation: 'h:k:l = 1/x:1/y:1/z', intuition: 'Reciprocal intercepts, then clear fractions.',
    hw: 'HW1 Q2', module: 'latticelab_homeworks.html?hw=hw1#miller', diagnosis: DIAG.miller0,
  }),
  Q({
    id: 'b-photon-k', cat: 'band', type: 'mc',
    prompt: 'Why is an optical transition drawn almost vertically on an E–k diagram?',
    choices: [
      { id: 'a', text: 'Photons carry energy but almost no crystal momentum' },
      { id: 'b', text: 'Electrons cannot change energy' },
      { id: 'c', text: 'k is position, so vertical means “stay put”' },
      { id: 'd', text: 'All semiconductors are direct' },
    ],
    correct: 'a',
    why: 'A visible photon’s k is tiny on the Brillouin-zone scale. Energy is paid; Δk is not. Si needs a phonon for the leftover Δk.',
    whyWrong: {
      b: 'The whole point is ΔE ≈ Eg.',
      c: 'k is crystal momentum, not a coordinate in the chip.',
      d: 'Si is the counterexample.',
    },
    equation: '\\text{photon: large }\\Delta E,\\text{ tiny }\\Delta k', intuition: 'Press Excite on the Si / GaAs pair.',
    hw: 'HW1 Q4', module: 'latticelab_homeworks.html?hw=hw1#ek', diagnosis: DIAG.gap_k,
  }),
  Q({
    id: 'b-si-emit', cat: 'band', type: 'scenario',
    prompt: 'A student says: “Si cannot emit light because it has an indirect bandgap.” Evaluate the statement.',
    choices: [
      { id: 'a', text: 'Correct: conservation of k forbids every Si photon' },
      { id: 'b', text: 'Too strong. Indirect emission needs a phonon and is inefficient, not a total ban. Absorption still happens with phonon help.' },
      { id: 'c', text: 'Wrong because Si is actually direct' },
      { id: 'd', text: 'Wrong because phonons are forbidden in Si' },
    ],
    correct: 'b',
    why: 'HW1 asks you to conserve E and k, not to declare silicon dark forever. That is why we do not make good Si LEDs.',
    whyWrong: {
      a: 'Phonon-assisted processes exist.',
      c: 'Si’s CB minimum is near X, not Γ.',
      d: 'The lattice vibrates. That is the phonon.',
    },
    equation: 'E\\text{ and }k\\text{ conservation}', intuition: 'Si plot: photon vertical, phonon horizontal.',
    hw: 'HW1 Q4', module: 'latticelab_homeworks.html?hw=hw1#ek', diagnosis: DIAG.gap_k,
  }),
  Q({
    id: 'b-direct', cat: 'band', type: 'mc',
    prompt: 'GaAs is direct. After a photon is absorbed at k = 0, why is no phonon required?',
    choices: [
      { id: 'a', text: 'CB minimum and VB maximum sit at the same k (Γ)' },
      { id: 'b', text: 'GaAs has no lattice' },
      { id: 'c', text: 'Direct means Eg = 0' },
      { id: 'd', text: 'Photons carry the entire Brillouin zone of momentum' },
    ],
    correct: 'a',
    why: 'Vertical in k-space already lands on the CB minimum.',
    whyWrong: {
      b: 'GaAs is a crystal.',
      c: 'GaAs Eg is 1.42 eV.',
      d: 'Photons are still nearly vertical.',
    },
    equation: 'E_g^{\\mathrm{dir}}\\text{ at }\\Gamma', intuition: 'The GaAs excite animation is a vertical jump.',
    hw: 'HW1 Q4', module: 'latticelab_homeworks.html?hw=hw1#ek', diagnosis: DIAG.gap_k,
  }),
  Q({
    id: 'p-eg-lg', cat: 'photon', type: 'predict',
    prompt: 'A semiconductor’s bandgap increases while T stays constant. Which way does its absorption-edge wavelength move?',
    choices: [
      { id: 'a', text: 'To shorter wavelength, because λg = hc/Eg' },
      { id: 'b', text: 'To longer wavelength, because a bigger gap “eats more red”' },
      { id: 'c', text: 'It does not move; only α’s height changes' },
      { id: 'd', text: 'To shorter wavelength because frequency fell' },
    ],
    correct: 'a',
    why: 'Larger Eg needs a more expensive photon. Expensive means larger E, which is smaller λ.',
    whyWrong: {
      b: 'Classic reversal of E ↔ λ.',
      c: 'The onset is λg itself.',
      d: 'Frequency rises when λ falls.',
    },
    equation: '\\lambda_g=hc/E_g', intuition: '1.9 eV → 653 nm. 2.42 eV → 512 nm.',
    hw: 'HW2 Q1a', module: 'latticelab_homeworks.html?hw=hw2&q=q1a', diagnosis: DIAG.lam_dir,
  }),
  Q({
    id: 'p-below', cat: 'photon', type: 'tf',
    prompt: 'True or false: A photon with E < Eg is absorbed and simply makes less energetic carriers.',
    choices: [{ id: 't', text: 'True' }, { id: 'f', text: 'False' }],
    correct: 'f',
    why: 'There is no allowed pair of band states to jump between. α stays ~0 for λ > λg in the teaching model.',
    whyWrong: { t: 'Cheaper tickets are not smaller electrons. They are not admitted.' },
    equation: 'E \\ge E_g', intuition: 'HW2 1.9 eV wafer is transparent in the deep red.',
    hw: 'HW2 Q1a', module: 'latticelab_homeworks.html?hw=hw2&q=q1a', diagnosis: DIAG.lam_dir,
  }),
  Q({
    id: 'p-white-inas', cat: 'photon', type: 'mc',
    prompt: 'White light (no reflection, no emission) hits InAs (Eg = 0.36 eV). What do you see through the wafer, and why?',
    choices: [
      { id: 'a', text: 'Nothing visible. Every visible photon has E ≫ 0.36 eV, so the leftover has no visible λ.' },
      { id: 'b', text: 'White, because InAs is a “narrow-gap metal-like” look' },
      { id: 'c', text: 'Infrared glow, which the eye reads as red' },
      { id: 'd', text: 'Green, because 0.36 eV is a green photon' },
    ],
    correct: 'a',
    why: 'You see the unabsorbed leftover. InAs’s λg is ~3440 nm, far infrared. The entire visible band is eaten.',
    whyWrong: {
      b: 'Narrow gap makes it more absorbing in the visible, not transparent.',
      c: 'The homework forbids emission. Infrared leftover is not a visible color.',
      d: '0.36 eV is infrared, not green. Green is ~2.2 eV.',
    },
    equation: 'E=1240/\\lambda', intuition: 'Compare with the 1.9 eV wafer, which leaks deep red.',
    hw: 'HW2 Q1b', module: 'latticelab_homeworks.html?hw=hw2&q=q1b', diagnosis: DIAG.lam_dir,
  }),
  Q({
    id: 'p-cds-635', cat: 'photon', type: 'mc',
    prompt: 'CdS has Eg = 2.42 eV. A 635 nm laser hits it. Absorbed? If the electron later recombines at the gap, what comes out?',
    choices: [
      { id: 'a', text: 'Not absorbed. E(635 nm) ≈ 1.95 eV < 2.42 eV. No band-edge emission from this photon.' },
      { id: 'b', text: 'Absorbed, emits 635 nm' },
      { id: 'c', text: 'Absorbed, emits 512 nm green' },
      { id: 'd', text: 'Absorbed, emits infrared' },
    ],
    correct: 'a',
    why: '1240/635 ≈ 1.95 eV, below 2.42 eV. The 470 nm laser is the CdS yes. Emission, when it happens, is 1240/2.42 ≈ 512 nm, not the laser color.',
    whyWrong: {
      b: 'Absorption λ is not emission λ, and this λ is not even absorbed.',
      c: 'That is the emit color if it had been absorbed (the 470 nm case).',
      d: 'CdS’s gap is green, not IR.',
    },
    equation: 'E=1240/\\lambda', intuition: 'Ticket in vs gap as the way out.',
    hw: 'HW2 Q1c', module: 'latticelab_homeworks.html?hw=hw2&q=q1c', diagnosis: DIAG.lam_dir,
  }),
  Q({
    id: 'p-cdse-470', cat: 'photon', type: 'mc',
    prompt: 'CdSe (Eg = 1.74 eV) absorbs 470 nm. What is the near-band-edge emission, conceptually?',
    choices: [
      { id: 'a', text: 'Still 470 nm, because energy is conserved exactly' },
      { id: 'b', text: 'About 713 nm (red). Extra energy is dumped as heat on the way down to Ec.' },
      { id: 'c', text: 'Ultraviolet, because the electron was “excited harder”' },
      { id: 'd', text: 'No emission is possible in a direct gap' },
    ],
    correct: 'b',
    why: 'Thermalization to the band edge. λemit ≈ 1240/1.74 ≈ 713 nm. Blue in, red out.',
    whyWrong: {
      a: 'Conservation of energy includes phonons / heat.',
      c: 'Harder excitation still relaxes to Ec.',
      d: 'Direct gaps are the efficient emitters.',
    },
    equation: '\\lambda_{\\mathrm{emit}}\\approx hc/E_g', intuition: 'HW2 Q1c table.',
    hw: 'HW2 Q1c', module: 'latticelab_homeworks.html?hw=hw2&q=q1c', diagnosis: DIAG.lam_dir,
  }),
  Q({
    id: 'f-half', cat: 'fermi', type: 'mc',
    prompt: 'For T > 0, what is f(EF), and what does that number mean?',
    choices: [
      { id: 'a', text: '1/2. Probability that a state at EF is occupied — not “half an electron.”' },
      { id: 'b', text: '1, because everything below EF is full' },
      { id: 'c', text: '0, because EF is empty by definition' },
      { id: 'd', text: 'It depends on doping' },
    ],
    correct: 'a',
    why: 'Plug E = EF: the exponential is 1, so f = 1/2. Doping moves EF; it does not change f(EF).',
    whyWrong: {
      b: 'That is the T = 0 story below EF, and even then the point E = EF is the step edge.',
      c: 'EF is not an empty level.',
      d: 'Doping slides EF. The pivot stays 1/2.',
    },
    equation: 'f(E_F)=1/2', intuition: 'Amber pivot on the HW1 Fermi plot.',
    hw: 'HW1 Q5', module: 'latticelab_homeworks.html?hw=hw1#fermi', diagnosis: DIAG.fd_meaning,
  }),
  Q({
    id: 'f-t0', cat: 'fermi', type: 'predict',
    prompt: 'Sketch, then choose: as T goes from 0 K to 300 K to 500 K at fixed EF, what happens to f(E)?',
    choices: [
      { id: 'a', text: 'A step becomes a wider and wider smear about the same 1/2 pivot' },
      { id: 'b', text: 'The whole curve slides up in energy' },
      { id: 'c', text: 'f(EF) falls from 1 to 0' },
      { id: 'd', text: 'The curve becomes a triangle' },
    ],
    correct: 'a',
    why: 'kT is the smear width. The pivot does not move unless EF moves.',
    whyWrong: {
      b: 'That would be an EF shift (doping), not a T smear.',
      c: 'f(EF) is 1/2 at every T > 0, and 1/2 at the step at T = 0.',
      d: 'It is a logistic / reverse-S, not a triangle.',
    },
    equation: 'f(E)=1/[1+e^{(E-E_F)/kT}]', intuition: 'Use the 0 / 300 / 500 buttons.',
    hw: 'HW1 Q5', module: 'latticelab_homeworks.html?hw=hw1#fermi', diagnosis: DIAG.fd_meaning,
  }),
  Q({
    id: 'f-not-count', cat: 'fermi', type: 'tf',
    prompt: 'True or false: f(E) tells you how many electrons sit at energy E.',
    choices: [{ id: 't', text: 'True' }, { id: 'f', text: 'False' }],
    correct: 'f',
    why: 'Number = density of states × occupancy. f is only the occupancy factor.',
    whyWrong: { t: 'You collapsed DOS × f into f.' },
    equation: 'n=\\int g_c(E)f(E)\\,dE', intuition: 'Empty gap: f can be 0.2 and still n ≈ 0 if there are no states.',
    hw: 'HW1 Q5', module: 'latticelab_homeworks.html?hw=hw1#fermi', diagnosis: DIAG.fd_meaning,
  }),
  Q({
    id: 'f-ef-not-home', cat: 'fermi', type: 'tf',
    prompt: 'True or false: EF is where the electrons physically sit.',
    choices: [{ id: 't', text: 'True' }, { id: 'f', text: 'False' }],
    correct: 'f',
    why: 'Most electrons sit in the valence band. EF is the dial that centers f(E). In a gapped semiconductor EF often sits in the gap, where there are no states.',
    whyWrong: { t: 'You treated a chemical potential as a parking lot.' },
    equation: 'E_F', intuition: 'Look at a midgap EF on the band + f(E) sketch.',
    hw: 'HW2 Q4', module: 'latticelab_homeworks.html?hw=hw2&q=q4ii', diagnosis: DIAG.ef_move,
  }),
  Q({
    id: 'd-inp-acc', cat: 'doping', type: 'mc',
    prompt: 'You need an effective p-type dopant in InP at 300 K. Where should the impurity level sit, using the course 3kT rule?',
    choices: [
      { id: 'a', text: 'Within ~78 meV of Ev, so it can steal a valence electron and leave a hole' },
      { id: 'b', text: 'Within 3kT of Ec, because p-type means electrons' },
      { id: 'c', text: 'At Ei, because that is “neutral”' },
      { id: 'd', text: 'Deep midgap, so it is a strong dopant' },
    ],
    correct: 'a',
    why: 'An acceptor is near Ev. 3kT(300 K) ≈ 78 meV. Midgap is a trap, not an effective dopant.',
    whyWrong: {
      b: 'Near Ec is a donor story (n-type).',
      c: 'Ei is not an impurity strategy.',
      d: 'Deep is the opposite of “effective dopant.”',
    },
    equation: 'E_I \\le 3kT', intuition: 'HW2 Q2a band sketch.',
    hw: 'HW2 Q2a', module: 'latticelab_homeworks.html?hw=hw2&q=q2a', diagnosis: DIAG.ionize,
  }),
  Q({
    id: 'd-cds-t', cat: 'doping', type: 'mc',
    prompt: 'Why can raising T from 300 K to 400 K make a CdS layer brighter in the HW2 impurity story?',
    choices: [
      { id: 'a', text: '3kT grows past EI (~90 meV). The near-Ev level ionizes as an acceptor, freeing holes, so recombination rises.' },
      { id: 'b', text: 'Hotter is always brighter' },
      { id: 'c', text: 'ni doubles, so everything emits twice' },
      { id: 'd', text: 'The gap shrinks to zero' },
    ],
    correct: 'a',
    why: '300 K: 3kT ≈ 78 meV < 90 meV → trap. 400 K: 3kT ≈ 103 meV > 90 meV → acceptor. Light is recombination, which needs both carrier types.',
    whyWrong: {
      b: 'The course forbids this collapse. Heat can also open nonradiative paths.',
      c: 'CdS’s gap is huge; ni is not the story.',
      d: 'Eg did not vanish.',
    },
    equation: 'E_I \\le 3kT', intuition: 'T → kT → ionization → holes → emission.',
    hw: 'HW2 Q2b', module: 'latticelab_homeworks.html?hw=hw2&q=q2bii', diagnosis: DIAG.ionize,
  }),
  Q({
    id: 'd-t0-nd', cat: 'doping', type: 'mc',
    prompt: 'Si with ND = 10^8 cm^{-3} at T = 0 K. What is honest to write?',
    choices: [
      { id: 'a', text: 'n ≈ 0 in the bands. Donors are frozen. f(E) is a step. EF sits at the donor level, not at Ei.' },
      { id: 'b', text: 'n = ND, because that is the definition of n-type' },
      { id: 'c', text: 'n = ni(0) = 10^{10}' },
      { id: 'd', text: 'p = ND' },
    ],
    correct: 'a',
    why: 'HW2 Q4(i). Complete ionization is a temperature statement, not a tattoo.',
    whyWrong: {
      b: 'n = ND is an extrinsic, ionized checklist.',
      c: 'ni(0) = 0. 10^{10} is the 300 K Si number.',
      d: 'Wrong carrier and wrong T.',
    },
    equation: 'T=0\\text{ step }f(E)', intuition: 'Open Q4(i) and look at the frozen donor.',
    hw: 'HW2 Q4(i)', module: 'latticelab_homeworks.html?hw=hw2&q=q4i', diagnosis: DIAG.ionize,
  }),
  Q({
    id: 'd-comp', cat: 'doping', type: 'mc',
    prompt: 'NA = 10^{16} cm^{-3}, ND = 10^3 cm^{-3}, Si at 300 K, ni = 10^{10} cm^{-3}. Type, and who is the majority?',
    choices: [
      { id: 'a', text: 'p-type. p ≈ NA. ND is a rounding error.' },
      { id: 'b', text: 'n-type, because ND is nonzero' },
      { id: 'c', text: 'Intrinsic, because both dopings are present' },
      { id: 'd', text: 'n-type, n = ND, p = NA together' },
    ],
    correct: 'a',
    why: 'NA ≫ ND and NA ≫ ni. Net acceptors. Then n = ni²/p.',
    whyWrong: {
      b: 'Nonzero ND is not a type name.',
      c: 'Compensation back to intrinsic needs NA ≈ ND.',
      d: 'Never write both majority shortcuts at once.',
    },
    equation: 'p\\approx N_A,\\; n=n_i^2/p', intuition: 'HW2 Q3(ii).',
    hw: 'HW2 Q3(ii)', module: 'latticelab_homeworks.html?hw=hw2&q=q3ii', diagnosis: DIAG.maj_both,
  }),
  Q({
    id: 'd-na10', cat: 'doping', type: 'mc',
    prompt: 'Si, 300 K, NA = 10 cm^{-3}, ND = 0. Why is this not “p-type with p = 10”?',
    choices: [
      { id: 'a', text: 'NA ≪ ni (10^{10}). Intrinsic pairs own the carriers. n ≈ p ≈ ni.' },
      { id: 'b', text: 'You forgot to convert to m^{-3}' },
      { id: 'c', text: 'Acceptors never ionize in Si' },
      { id: 'd', text: 'p = 10 is correct; ni is irrelevant' },
    ],
    correct: 'a',
    why: 'The majority shortcut has a checklist. NA ≫ ni failed. HW2 Q3(i) is this trap.',
    whyWrong: {
      b: 'Units are already cm^{-3}.',
      c: 'Shallow acceptors do ionize at 300 K. There are just almost none.',
      d: 'That is the trap.',
    },
    equation: 'N_A \\ll n_i \\Rightarrow n\\approx p\\approx n_i', intuition: 'Compare 10 with 10^{10}.',
    hw: 'HW2 Q3(i)', module: 'latticelab_homeworks.html?hw=hw2&q=q3i', diagnosis: DIAG.maj_both,
  }),
  Q({
    id: 'car-ef-n', cat: 'carriers', type: 'predict',
    prompt: 'EF moves closer to Ec at fixed T. Without calculating, what happens to n and p?',
    choices: [
      { id: 'a', text: 'n rises exponentially. p falls so that np stays ni².' },
      { id: 'b', text: 'n and p both rise, because EF “creates carriers”' },
      { id: 'c', text: 'n falls because states above EF empty' },
      { id: 'd', text: 'Nothing: EF is only a label' },
    ],
    correct: 'a',
    why: 'n = ni exp((EF−Ei)/kT). The hole exponent flips. Product forgets EF.',
    whyWrong: {
      b: 'Equilibrium doping redistributes, it does not create pairs.',
      c: 'Closer to Ec fills the conduction tail.',
      d: 'EF is the occupation dial.',
    },
    equation: 'n=n_i e^{(E_F-E_i)/kT}', intuition: 'Drag EF on the equation map.',
    hw: 'HW2 Q3, Q4', module: 'eqrel.html', diagnosis: DIAG.ef_move,
  }),
  Q({
    id: 'car-np-led', cat: 'carriers', type: 'tf',
    prompt: 'True or false: np = ni² in the injection region of a forward-biased LED.',
    choices: [{ id: 't', text: 'True' }, { id: 'f', text: 'False' }],
    correct: 'f',
    why: 'Mass action needs one EF. Injection is two quasi-Fermi levels. np exceeds ni²; that is the point of an LED.',
    whyWrong: { t: 'You used an equilibrium law in a driven device.' },
    equation: 'np=n_i^2\\text{ (equilibrium only)}', intuition: 'EqRel “when not to use it.”',
    hw: 'Equation sheet + EqRel', module: 'exam1.html?mode=sheet&eq=e_np', diagnosis: DIAG.inject,
  }),
  Q({
    id: 'car-gaas-ni', cat: 'carriers', type: 'mc',
    prompt: 'GaAs at 300 K, NA = 10^{11} cm^{-3}, ND = 0, ni = 10^6 cm^{-3}. Who owns p?',
    choices: [
      { id: 'a', text: 'Acceptors. NA ≫ ni, so p ≈ NA, n = ni²/p.' },
      { id: 'b', text: 'Intrinsic pairs, because GaAs is “always intrinsic”' },
      { id: 'c', text: 'Electrons, because μn is huge' },
      { id: 'd', text: 'p = n = 10^{11}' },
    ],
    correct: 'a',
    why: '10^{11} vs 10^6. The checklist passes. Huge μn affects σ’s split, not the type name.',
    whyWrong: {
      b: 'GaAs is easy to dope past its tiny ni.',
      c: 'Mobility is not a type.',
      d: 'Mass action forbids n = p = NA unless ni = NA.',
    },
    equation: 'p\\approx N_A', intuition: 'HW2 Q3(iv).',
    hw: 'HW2 Q3(iv)', module: 'latticelab_homeworks.html?hw=hw2&q=q3iv', diagnosis: DIAG.maj_both,
  }),
  Q({
    id: 'tr-mu-sigma', cat: 'transport', type: 'mc',
    prompt: 'Two samples have the same n and p. Sample A has twice the electron mobility of Sample B. Which has larger conductivity, and why?',
    choices: [
      { id: 'a', text: 'A. σ = q(nμn + pμp). μn doubled, n fixed, so the electron channel doubled.' },
      { id: 'b', text: 'Equal, because conductivity is only concentration' },
      { id: 'c', text: 'B, because slower carriers scatter less' },
      { id: 'd', text: 'A only if it is p-type' },
    ],
    correct: 'a',
    why: 'Mobility is a separate multiplier from concentration.',
    whyWrong: {
      b: 'That is the trap the sheet is written to block.',
      c: 'Slower is smaller μ, smaller σ.',
      d: 'The electron term still grows in a p-type sample; it may just be a small term.',
    },
    equation: '\\sigma=q(n\\mu_n+p\\mu_p)', intuition: 'Hold n,p,E. Raise μ.',
    hw: 'HW2 Q3 σ', module: 'exam1.html?mode=sheet&eq=e_sigma', diagnosis: DIAG.ef_move,
  }),
  Q({
    id: 'tr-r', cat: 'transport', type: 'mc',
    prompt: 'A uniform bar: L doubles and A doubles. ρ is unchanged. What happens to R?',
    choices: [
      { id: 'a', text: 'R is unchanged. R = ρL/A.' },
      { id: 'b', text: 'R doubles' },
      { id: 'c', text: 'R halves' },
      { id: 'd', text: 'R quadruples' },
    ],
    correct: 'a',
    why: 'Geometry ratio L/A is invariant.',
    whyWrong: {
      b: 'You followed L and ignored A.',
      c: 'You followed A and ignored L.',
      d: 'There is no L²/A² here.',
    },
    equation: 'R=\\rho L/A', intuition: 'ρ is material; R is material × shape.',
    hw: 'Equation sheet', module: 'exam1.html?mode=sheet&eq=e_r', diagnosis: DIAG.beer,
  }),
  Q({
    id: 'tr-j', cat: 'transport', type: 'mc',
    prompt: 'If E doubles while σ stays fixed, what happens to J?',
    choices: [
      { id: 'a', text: 'J doubles. J = σE is linear.' },
      { id: 'b', text: 'J is unchanged because current is quantized' },
      { id: 'c', text: 'J grows as e^{qE/kT}' },
      { id: 'd', text: 'J halves' },
    ],
    correct: 'a',
    why: 'Local Ohm. Do not steal the Shockley exponential.',
    whyWrong: {
      b: 'J is a density, not a single-electron mystery.',
      c: 'That exponential belongs to a barrier, not a resistor.',
      d: 'Wrong direction.',
    },
    equation: 'J=\\sigma\\mathcal{E}', intuition: 'Straight J–E line.',
    hw: 'Equation sheet', module: 'exam1.html?mode=sheet&eq=e_je', diagnosis: DIAG.inject,
  }),
  Q({
    id: 't-regimes', cat: 'temperature', type: 'rank',
    prompt: 'An n-doped semiconductor is heated from very low T through device T to very high T. Rank the regimes in the order they appear.',
    choices: [
      { id: 'a', text: 'Freeze-out' },
      { id: 'b', text: 'Extrinsic (n ≈ ND)' },
      { id: 'c', text: 'Intrinsic (ni overtakes ND)' },
    ],
    correct: ['a', 'b', 'c'],
    why: 'Not enough kT to ionize → donors ionized and own n → pairs own n.',
    whyWrong: {},
    equation: 'n(T)', intuition: 'HW2 Q5b sketch.',
    hw: 'HW2 Q5b', module: 'latticelab_homeworks.html?hw=hw2&q=q5b', diagnosis: DIAG.regime,
  }),
  Q({
    id: 't-plateau', cat: 'temperature', type: 'mc',
    prompt: 'Why is the middle of an n-doped n-vs-T plot flat?',
    choices: [
      { id: 'a', text: 'n is pinned to a fixed number of ionized donors. Raising T does not create more doping electrons.' },
      { id: 'b', text: 'Temperature stopped mattering' },
      { id: 'c', text: 'μ fell exactly enough to cancel ni' },
      { id: 'd', text: 'The plot uses a broken axis' },
    ],
    correct: 'a',
    why: 'The plateau is n ≈ ND, not “T is irrelevant.” Later ni(T) climbs through the plateau.',
    whyWrong: {
      b: 'T still sets ionization completeness and, later, ni.',
      c: 'This plot is n(T), not σ(T).',
      d: 'The physics is the flatness.',
    },
    equation: 'n\\approx N_D', intuition: 'Horizontal ND line on the HW2 temp viz.',
    hw: 'HW2 Q5b', module: 'latticelab_homeworks.html?hw=hw2&q=q5b', diagnosis: DIAG.regime,
  }),
  Q({
    id: 't-eg-onset', cat: 'temperature', type: 'mc',
    prompt: 'Why does a smaller-bandgap semiconductor generally enter the intrinsic regime at a lower temperature?',
    choices: [
      { id: 'a', text: 'ni ∝ exp(−Eg/2kT). Smaller Eg → ni grows past ND sooner.' },
      { id: 'b', text: 'Small-gap crystals cannot be doped' },
      { id: 'c', text: 'Phonons are slower in small-gap crystals' },
      { id: 'd', text: 'μn is always smaller, so we redefine “intrinsic”' },
    ],
    correct: 'a',
    why: 'HW2 Q5c: same ND, GaAs (1.42 eV) stays extrinsic longer than Si (1.12 eV). Ge (0.66 eV) fails the 10% spec first in Q5d.',
    whyWrong: {
      b: 'Ge and InAs are routinely doped.',
      c: 'Not the mechanism.',
      d: 'Intrinsic is an n,p statement, not a mobility rename.',
    },
    equation: 'n_i\\propto e^{-E_g/2kT}', intuition: 'Overlay Si and GaAs.',
    hw: 'HW2 Q5c, Q5d', module: 'latticelab_homeworks.html?hw=hw2&q=q5c', diagnosis: DIAG.regime,
  }),
  Q({
    id: 't-tmax', cat: 'temperature', type: 'scenario',
    prompt: 'A Ge junction is designed so n ≈ ND and p ≈ NA. Why does a high enough T break that design even though the junction still exists?',
    choices: [
      { id: 'a', text: 'Intrinsic pairs swamp the designed concentrations. Doping no longer owns n and p.' },
      { id: 'b', text: 'The crystal melts at 80 °C' },
      { id: 'c', text: 'Donors fall out of the lattice' },
      { id: 'd', text: 'Vbi becomes infinite' },
    ],
    correct: 'a',
    why: 'HW2 Q5d: 10% band fails when ni ≈ 0.332 NA. Ge’s small gap hits that ni at a much lower T than Si.',
    whyWrong: {
      b: 'Ge melts far higher. This is an electrical spec.',
      c: 'The impurities are still there. They are just outnumbered.',
      d: 'Vbi actually tends to fall as ni rises.',
    },
    equation: 'p=N_A/2+\\sqrt{(N_A/2)^2+n_i^2}', intuition: 'Watch the gauges on Q5d.',
    hw: 'HW2 Q5d', module: 'latticelab_homeworks.html?hw=hw2&q=q5d', diagnosis: DIAG.regime,
  }),
  Q({
    id: 't-rank-ni', cat: 'temperature', type: 'rank',
    prompt: 'Rank these by expected ni(300 K), largest first, using only the gaps: Ge 0.66 eV, Si 1.12 eV, GaAs 1.42 eV.',
    choices: [
      { id: 'a', text: 'Ge' },
      { id: 'b', text: 'Si' },
      { id: 'c', text: 'GaAs' },
    ],
    correct: ['a', 'b', 'c'],
    why: 'ni collapses exponentially as Eg grows. Table: Ge ~10^{13}, Si ~10^{10}, GaAs ~10^6 cm^{-3}.',
    whyWrong: {},
    equation: 'n_i\\propto e^{-E_g/2kT}', intuition: 'Opposite of ranking by Eg.',
    hw: 'HW2 table', module: 'exam1.html?mode=sheet&eq=e_table', diagnosis: DIAG.regime,
  }),
  Q({
    id: 't-heat-sigma', cat: 'temperature', type: 'tf',
    prompt: 'True or false: Heating a semiconductor always decreases its conductivity.',
    choices: [{ id: 't', text: 'True' }, { id: 'f', text: 'False' }],
    correct: 'f',
    why: 'In freeze-out or intrinsic, n(T) or p(T) can rise enough to beat any μ drop. Name the regime first.',
    whyWrong: { t: 'You imported a metal story.' },
    equation: '\\sigma=q(n\\mu_n+p\\mu_p)', intuition: 'Intrinsic Si: ni explodes with T.',
    hw: 'HW2 Q5', module: 'latticelab_homeworks.html?hw=hw2&q=q5b', diagnosis: DIAG.regime,
  }),
  Q({
    id: 'pn-fwd', cat: 'pn', type: 'chain',
    prompt: 'Forward bias is increased. Put these in causal order.',
    choices: [
      { id: 'a', text: 'Barrier q(Vbi−VA) drops' },
      { id: 'b', text: 'Depletion width shrinks' },
      { id: 'c', text: 'Majority injection rises' },
      { id: 'd', text: 'Diode current rises exponentially' },
    ],
    correct: ['a', 'b', 'c', 'd'],
    why: 'Bias first changes the barrier. Width is the electrostatic consequence. Injection is the carrier consequence. Shockley is the current consequence.',
    whyWrong: {},
    equation: 'I=I_0(e^{qV_A/kT}-1)', intuition: 'Story Mode’s last two rail stops.',
    hw: 'PN lab / Story', module: 'pn_lab.html?mode=story', diagnosis: DIAG.inject,
  }),
  Q({
    id: 'pn-w-dop', cat: 'pn', type: 'mc',
    prompt: 'NA or ND increases (abrupt junction, fixed VA). What happens to W, and why?',
    choices: [
      { id: 'a', text: 'W generally falls. More uncovered charge per length means you need less length to support Vbi−VA.' },
      { id: 'b', text: 'W rises because there is more charge to uncover' },
      { id: 'c', text: 'W is independent of doping' },
      { id: 'd', text: 'Only xn grows; xp is fixed' },
    ],
    correct: 'a',
    why: 'Poisson + area match. The lighter-doped side still owns more of W.',
    whyWrong: {
      b: 'More charge per length is a thinner slab, not a thicker one.',
      c: 'Look at the square-root doping factors.',
      d: 'Both sides move; the ratio is ND/NA.',
    },
    equation: 'W\\propto 1/\\sqrt{N_{\\mathrm{eff}}}', intuition: 'PN lab doping sliders.',
    hw: 'PN lab', module: 'pn_lab.html?mode=lab', diagnosis: DIAG.w_dop,
  }),
  Q({
    id: 'pn-side', cat: 'pn', type: 'mc',
    prompt: 'ND ≫ NA. Which side contains most of the depletion width, and why?',
    choices: [
      { id: 'a', text: 'The P-side. NA xp = ND xn, so the lighter side must be thicker.' },
      { id: 'b', text: 'The N-side, because that is where the electrons live' },
      { id: 'c', text: 'They are always equal' },
      { id: 'd', text: 'Neither: depletion exists only on one side of a one-sided junction, the heavy side' },
    ],
    correct: 'a',
    why: 'Charge neutrality of the uncovered ions. One-sided p+n still puts almost all W in the light n.',
    whyWrong: {
      b: 'Majority location is not W location.',
      c: 'Only if NA = ND.',
      d: 'The heavy side’s piece is thin, not zero, and it is the light side that is wide.',
    },
    equation: 'N_A x_p=N_D x_n', intuition: 'PN lab charge-balance bars.',
    hw: 'PN exam intuition', module: 'pn_lab.html?mode=lab', diagnosis: DIAG.w_dop,
  }),
  Q({
    id: 'pn-rev', cat: 'pn', type: 'ms',
    prompt: 'Reverse |VA| increases. Select every correct consequence.',
    choices: [
      { id: 'a', text: 'Barrier rises' },
      { id: 'b', text: 'W grows' },
      { id: 'c', text: 'Majority diffusion over the barrier is suppressed' },
      { id: 'd', text: 'Current explodes as e^{+q|VA|/kT}' },
    ],
    correct: ['a', 'b', 'c'],
    why: 'Reverse current sits near −I0. The exponential explosion is forward.',
    whyWrong: { d: 'Wrong bias direction for Shockley growth.' },
    equation: 'I\\approx -I_0', intuition: 'I–V marker in reverse.',
    hw: 'PN lab', module: 'pn_lab.html?mode=lab', diagnosis: DIAG.inject,
  }),
  Q({
    id: 'o-beer', cat: 'optics', type: 'mc',
    prompt: 'α doubles while x is fixed. Does transmitted intensity halve?',
    choices: [
      { id: 'a', text: 'No. I = I0 e^{−αx}, so doubling α squares the remaining fraction. That is 1/2 only for a special αx.' },
      { id: 'b', text: 'Yes, because absorption is linear' },
      { id: 'c', text: 'Yes, by definition of α' },
      { id: 'd', text: 'Intensity doubles' },
    ],
    correct: 'a',
    why: 'dI = −α I dx integrates to an exponential. Linear thinking is the trap.',
    whyWrong: {
      b: 'Each slice eats a fraction of what remains, not a fixed chunk of I0.',
      c: 'α’s definition is that differential statement, which is exponential in x.',
      d: 'Wrong direction.',
    },
    equation: 'I=I_0 e^{-\\alpha x}', intuition: 'Sheet optics card.',
    hw: 'Equation sheet', module: 'exam1.html?mode=sheet&eq=e_beer', diagnosis: DIAG.beer,
  }),
  Q({
    id: 'eq-chain-nd', cat: 'equations', type: 'chain',
    prompt: 'ND increases (extrinsic, ionized, NA ≈ 0). Order the downstream effects.',
    choices: [
      { id: 'a', text: 'EF approaches Ec' },
      { id: 'b', text: 'n rises' },
      { id: 'c', text: 'p falls through np = ni²' },
      { id: 'd', text: 'σ generally rises (q n μn grows)' },
    ],
    correct: ['a', 'b', 'c', 'd'],
    why: 'Doping → EF → occupation → mass action → conductivity. μ may fall a little; the homework first story is the n channel.',
    whyWrong: {},
    equation: 'n\\approx N_D', intuition: 'Equation Relationship Visualizer, drive: doping.',
    hw: 'HW2 Q3', module: 'eqrel.html', diagnosis: DIAG.ef_move,
  }),
  Q({
    id: 'eq-error-student', cat: 'equations', type: 'scenario',
    prompt: 'A fictional student writes: “The sample is n-type so n = ND and also p = NA. Then σ = q(nμn + pμp).” What is wrong?',
    choices: [
      { id: 'a', text: 'n = ND and p = NA describe opposite crystals. One sample has one majority; the minority is ni² over that majority.' },
      { id: 'b', text: 'σ never includes holes' },
      { id: 'c', text: 'n-type means n = 0' },
      { id: 'd', text: 'Nothing. This is the standard solve.' },
    ],
    correct: 'a',
    why: 'Error analysis: the σ formula is fine; the inputs are illegal together.',
    whyWrong: {
      b: 'Holes are the second term. In p-type they are the term.',
      c: 'n-type means electrons are the majority.',
      d: 'This is a common exam zero.',
    },
    equation: 'np=n_i^2', intuition: 'Name the type, then one shortcut, then mass action.',
    hw: 'HW2 Q3', module: 'latticelab_homeworks.html?hw=hw2&q=q3ii', diagnosis: DIAG.maj_both,
  }),
  Q({
    id: 'eq-light-lg', cat: 'equations', type: 'calc',
    prompt: 'Light calculation: Eg = 1.9 eV. What is λg in nm using 1240 eV·nm? (Nearest integer.)',
    choices: [
      { id: 'a', text: '653' },
      { id: 'b', text: '1240' },
      { id: 'c', text: '1900' },
      { id: 'd', text: '380' },
    ],
    correct: 'a',
    why: '1240 / 1.9 = 652.6 nm → 653 nm. This number is the HW2 Q1a mark on α(λ).',
    whyWrong: {
      b: 'That is hc, not λg.',
      c: 'You multiplied instead of dividing.',
      d: 'That is a violet wavelength, not this gap.',
    },
    equation: '\\lambda_g=1240/E_g', intuition: 'Then mark it on α(λ).',
    hw: 'HW2 Q1a', module: 'latticelab_homeworks.html?hw=hw2&q=q1a', diagnosis: DIAG.lam_dir,
  }),
  Q({
    id: 'eq-3kt', cat: 'equations', type: 'calc',
    prompt: 'Light calculation: 3kT at 300 K is about how many meV? (k ≈ 8.62×10^{-5} eV/K.)',
    choices: [
      { id: 'a', text: '78' },
      { id: 'b', text: '26' },
      { id: 'c', text: '300' },
      { id: 'd', text: '8.6' },
    ],
    correct: 'a',
    why: 'kT ≈ 26 meV, times 3 ≈ 78 meV. That is the HW2 ionization window. 400 K is ~103 meV.',
    whyWrong: {
      b: 'That is 1×kT, not 3kT.',
      c: 'That is the temperature in kelvin, not meV.',
      d: 'That is k in eV/K, missing T and the 3.',
    },
    equation: '3kT', intuition: 'CdS EI ≈ 90 meV sits between 78 and 103.',
    hw: 'HW2 Q2', module: 'latticelab_homeworks.html?hw=hw2&q=q2bi', diagnosis: DIAG.ionize,
  }),
];

export const BANK = [...OBJECTIVE, ...WRITTEN];

export function questionById(id) {
  return BANK.find((q) => q.id === id);
}

export function bankByCat(cat) {
  return BANK.filter((q) => q.cat === cat);
}

export function rubricCat(cat) {
  if (cat === 'miller' || cat === 'crystal') return 'crystal';
  if (cat === 'optics') return 'photon';
  return cat;
}
