/**
 * Exam 1 equation sheet — conceptual mastery cards.
 * Scope is HW1, HW2, and the sheet relationships listed by the course.
 */

export const SHEET = {
  e_hc: {
    id: 'e_hc', family: 'photon', name: 'Photon energy',
    latex: 'E = h\\nu = hc/\\lambda',
    words: 'A shorter wavelength is a higher-frequency photon, so each packet carries more energy. λ sits in the denominator.',
    vars: [
      { s: 'E', m: 'photon energy', u: 'eV (or J)' },
      { s: 'ν, f', m: 'frequency', u: 's^{-1}' },
      { s: 'λ', m: 'wavelength', u: 'nm on the homework sheet' },
      { s: 'hc', m: '1240 eV·nm teaching constant', u: 'eV·nm' },
    ],
    cause: 'If λ halves at fixed c, E doubles. If Eg rises, the longest absorbable λ shortens.',
    graph: 'E vs λ is a hyperbola. α(λ) stays ~0 until λ = λg, then rises (steep for a direct gap).',
    story: 'The wave must cover c meters in one second. Closer crests mean more oscillations per second. Quantum mechanics assigns energy hf to one oscillation.',
    valid: 'One monochromatic photon. Vacuum hc. Not the beam’s total power (that is photon flux × E).',
    chain: 'λ → E → compare with Eg → absorb? → if yes, emission after relaxation is ~Eg, not the laser λ.',
    trap: 'Red is not “more energy because it looks longer.” Red is long-λ, low-E.',
    check: 'Eg increases at fixed T. Which way does the absorption-edge wavelength move?',
    hw: 'HW2 Q1a–c. White-light leftover color is the unabsorbed tail.',
    module: 'latticelab_homeworks.html?hw=hw2&q=q1a',
  },
  e_lg: {
    id: 'e_lg', family: 'photon', name: 'Gap wavelength',
    latex: '\\lambda_g = hc/E_g',
    words: 'The cheapest optical jump costs Eg. The longest photon that can still pay is hc/Eg.',
    vars: [
      { s: 'λg', m: 'absorption-edge wavelength', u: 'nm' },
      { s: 'Eg', m: 'bandgap', u: 'eV' },
    ],
    cause: 'Eg ↑ ⇒ λg ↓. A 1.9 eV gap has λg ≈ 653 nm. InAs (0.36 eV) has λg in the infrared.',
    graph: 'Mark λg on an α(λ) sketch. Zero to the long-λ side, rise to the short-λ side.',
    story: 'No valence electron can reach the conduction band unless the photon covers Eg. Extra photon energy becomes heat after the electron thermalizes to Ec.',
    valid: 'Sharp-onset teaching model. Indirect gaps still have a λg; α just rises slowly because a phonon must help.',
    chain: 'Eg ↑ → λg ↓ → absorption edge moves blue.',
    trap: 'A larger gap does not “eat more of the red.” It needs a more expensive (bluer) photon.',
    check: 'CdS Eg = 2.42 eV. Can 635 nm be absorbed? Reason with 1240/λ, no calculator theater.',
    hw: 'HW2 Q1. CdS/CdSe laser table.',
    module: 'latticelab_homeworks.html?hw=hw2&q=q1c',
  },
  e_f: {
    id: 'e_f', family: 'fermi', name: 'Fermi–Dirac occupancy',
    latex: 'f(E)=\\dfrac{1}{1+e^{(E-E_F)/kT}}',
    words: 'Pick an energy. f is the chance a state there is occupied. It is not a count of electrons.',
    vars: [
      { s: 'f(E)', m: 'occupation probability', u: 'dimensionless, 0 to 1' },
      { s: 'EF', m: 'Fermi level (chemical potential)', u: 'eV' },
      { s: 'T', m: 'temperature', u: 'K' },
      { s: 'kT', m: 'thermal energy', u: 'eV (~26 meV at 300 K)' },
    ],
    cause: 'T ↑ smears the 1→0 drop over a few kT. f(EF) stays 1/2 for every T > 0. T = 0 is a step.',
    graph: 'Energy vertical, f horizontal: a step at 0 K; a soft reverse-S at 300 K; a wider smear at 500 K. Amber pivot at (0.5, EF).',
    story: 'Fermions cannot share a state. The grand partition function of one state produces this fraction. Heat blurs the border around EF.',
    valid: 'Equilibrium, one EF. Under bias or light you need two quasi-Fermi levels.',
    chain: 'T ↑ → f smears → states above EF gain a tail → n and p both grow if the crystal is intrinsic.',
    trap: 'f(EF)=1/2 is not “half an electron sitting at EF.” It is a probability for whatever states exist at that energy.',
    check: 'Without numbers: if T rises at fixed EF, does f(EF) change?',
    hw: 'HW1 Q5. HW2 Q4 band + f(E) sketches, including T = 0.',
    module: 'latticelab_homeworks.html?hw=hw1#fermi',
  },
  e_n_nc: {
    id: 'e_n_nc', family: 'carriers', name: 'Electrons from Ec',
    latex: 'n = N_C\\,e^{-(E_C-E_F)/kT}',
    words: 'How close EF sits to Ec sets how full the conduction band is. The leftover occupation is a Boltzmann tail.',
    vars: [
      { s: 'n', m: 'electron concentration', u: 'cm^{-3}' },
      { s: 'NC', m: 'effective conduction DOS', u: 'cm^{-3}' },
      { s: 'Ec−EF', m: 'distance from EF up to Ec', u: 'eV' },
    ],
    cause: 'EF moves toward Ec ⇒ n rises exponentially. ~60 meV closer at 300 K multiplies n by about 10.',
    graph: 'n vs (EF−Ei) is exponential on a linear plot, a straight line on a log plot.',
    story: 'Pile the parabolic conduction states into an equivalent NC at Ec, then multiply by f(Ec) in the Boltzmann limit.',
    valid: 'Nondegenerate: EF at least a few kT below Ec. Fails for heavy n-type (Fermi integrals).',
    chain: 'ND ↑ → EF toward Ec → n ↑ → p ↓ by mass action.',
    trap: 'NC is not the number of electrons. It is an equivalent state count.',
    check: 'EF rises at fixed T. What happens to n? To p?',
    hw: 'HW2 Q3 and Q4 band diagrams.',
    module: 'eqrel.html',
  },
  e_p_nv: {
    id: 'e_p_nv', family: 'carriers', name: 'Holes from Ev',
    latex: 'p = N_V\\,e^{-(E_F-E_V)/kT}',
    words: 'A hole is a missing valence electron. If EF sits well above Ev, almost every valence state is full, so holes are rare.',
    vars: [
      { s: 'p', m: 'hole concentration', u: 'cm^{-3}' },
      { s: 'NV', m: 'effective valence DOS', u: 'cm^{-3}' },
    ],
    cause: 'EF rises ⇒ (EF−Ev) grows ⇒ p falls exponentially. Partner of the n formula.',
    graph: 'Mirror of n: log p vs EF is a line of opposite slope.',
    story: 'Hole occupation is 1−f. In the Boltzmann limit that is an exponential in (EF−E).',
    valid: 'Nondegenerate p-type. Not freeze-out, not EF inside the valence band.',
    chain: 'NA ↑ → EF toward Ev → p ↑ → n ↓.',
    trap: 'Holes are not extra +particles poured into the lattice. They are missing valence electrons.',
    check: 'Why does the exponent flip sign relative to n = NC exp(−(Ec−EF)/kT)?',
    hw: 'HW2 Q3 p-type Si rows.',
    module: 'eqrel.html',
  },
  e_n_ni: {
    id: 'e_n_ni', family: 'carriers', name: 'Electrons from Ei',
    latex: 'n = n_i\\,e^{(E_F-E_i)/kT}',
    words: 'When undoped, n = ni and EF = Ei. Each kT that EF climbs above Ei multiplies n by e.',
    vars: [
      { s: 'ni', m: 'intrinsic concentration', u: 'cm^{-3}' },
      { s: 'Ei', m: 'intrinsic Fermi level', u: 'eV' },
    ],
    cause: 'EF − Ei = +kT ln 10 ⇒ n × 10. Same rewrite as the NC form.',
    graph: 'Same exponential as e_n_nc, zero of energy moved to Ei.',
    story: 'Divide n = NC exp(−(Ec−EF)/kT) by ni = NC exp(−(Ec−Ei)/kT). NC cancels.',
    valid: 'Equilibrium Boltzmann. Under injection use a quasi-Fermi level Fn.',
    chain: 'This times the hole partner is mass action.',
    trap: 'This is not a different n. It is the same Boltzmann count with a friendlier zero.',
    check: 'On a sketched band diagram, EF is 2kT above Ei. Is n about 7×ni or 2×ni?',
    hw: 'HW2 Q4 “mark EF relative to Ei.”',
    module: 'eqrel.html',
  },
  e_p_ni: {
    id: 'e_p_ni', family: 'carriers', name: 'Holes from Ei',
    latex: 'p = n_i\\,e^{(E_i-E_F)/kT}',
    words: 'The hole story is the electron story with the exponent flipped.',
    vars: [{ s: 'p', m: 'hole concentration', u: 'cm^{-3}' }],
    cause: 'Whatever multiplies n must divide p if np stays ni².',
    graph: 'p falls when n rises, product flat at fixed T.',
    story: '1−f in the valence band, referenced to Ei.',
    valid: 'One EF. Breaks when Fn ≠ Fp.',
    chain: 'n × p = ni² after the exponents cancel.',
    trap: 'Doping does not raise n and p together at equilibrium.',
    check: 'n rises by 100× at fixed T. What happens to p?',
    hw: 'HW2 Q3 minority calculations.',
    module: 'eqrel.html',
  },
  e_np: {
    id: 'e_np', family: 'carriers', name: 'Mass action',
    latex: 'np = n_i^2',
    words: 'At equilibrium you may trade electrons for holes, but you cannot change their product. T and Eg set the product.',
    vars: [
      { s: 'n, p', m: 'carrier concentrations', u: 'cm^{-3}' },
      { s: 'ni²', m: 'equilibrium product', u: 'cm^{-6}' },
    ],
    cause: 'EF moves: n and p trade. T rises: ni rises, so the product rises.',
    graph: 'n vs p on a log–log plot is a line of slope −1 at fixed T.',
    story: 'Two Boltzmann tails share one EF. Their EF pieces cancel. What remains is exp(−Eg/kT).',
    valid: 'Thermal equilibrium. Not a forward-biased junction or an LED under injection.',
    chain: 'p ≈ NA (checklist) → n = ni²/p.',
    trap: 'np = ni² is not a law of nature in a working diode. Injection is the point of a diode.',
    check: 'A student writes n = ND and p = NA in the same neutral region. What did they forget?',
    hw: 'HW2 Q3 every row after naming the majority.',
    module: 'eqrel.html',
  },
  e_nc: {
    id: 'e_nc', family: 'carriers', name: 'Effective DOS NC',
    latex: 'N_C = 2\\left(\\dfrac{2\\pi m_n^* kT}{h^2}\\right)^{3/2}',
    words: 'The conduction band has a pile of states near Ec. NC is that pile collapsed to one equivalent number at Ec. It grows as T^{3/2}.',
    vars: [
      { s: 'mn*', m: 'electron effective mass', u: 'kg' },
      { s: 'T', m: 'temperature', u: 'K' },
    ],
    cause: 'T ↑ ⇒ NC ↑ mildly. mn* ↑ ⇒ more states near Ec ⇒ NC ↑.',
    graph: 'NC vs T is a slow power law. It never beats the exp(−Eg/2kT) in ni.',
    story: 'Integrate a parabolic g_c(E)∝√(E−Ec) against a Boltzmann tail. The Γ(3/2) integral leaves T^{3/2}.',
    valid: 'Parabolic band, Boltzmann. Not a metal, not a quantum well.',
    chain: 'NC(T) and NV(T) feed ni ∝ T^{3/2} exp(−Eg/2kT).',
    trap: 'A bigger NC does not mean the crystal is n-type. Doping and EF still decide n.',
    check: 'Why does ni have a T^{3/2} prefactor at all?',
    hw: 'Background for HW2 Q5 linearized slope (the exponential still owns the plot).',
    module: 'eqrel.html',
  },
  e_nv: {
    id: 'e_nv', family: 'carriers', name: 'Effective DOS NV',
    latex: 'N_V = 2\\left(\\dfrac{2\\pi m_p^* kT}{h^2}\\right)^{3/2}',
    words: 'Same construction as NC, for the valence band and mp*.',
    vars: [{ s: 'mp*', m: 'hole effective mass', u: 'kg' }],
    cause: 'Heavier holes ⇒ larger NV ⇒ Ei sits slightly off midgap if NC ≠ NV.',
    graph: 'Same T^{3/2} as NC.',
    story: 'Parabolic valence band plus empty-state Boltzmann tail.',
    valid: 'Parabolic, nondegenerate.',
    chain: 'ni² = NC NV exp(−Eg/kT).',
    trap: 'NV is not “the number of holes.”',
    check: 'If NC > NV, does Ei sit above or below midgap?',
    hw: 'Sheet table: effective masses. HW2 uses ni(300) as given.',
    module: 'eqrel.html',
  },
  e_ni: {
    id: 'e_ni', family: 'temperature', name: 'Intrinsic concentration',
    latex: 'n_i \\propto T^{3/2}e^{-E_g/(2kT)}',
    words: 'Heat tries to throw pairs across the gap. A bigger gap or a colder crystal makes that exponentially rare.',
    vars: [
      { s: 'ni', m: 'intrinsic pair density', u: 'cm^{-3}' },
      { s: 'Eg', m: 'gap', u: 'eV' },
    ],
    cause: 'T ↑ ⇒ ni explodes. Eg ↑ ⇒ ni collapses. Ge becomes intrinsic sooner than Si.',
    graph: 'ln(ni/T^{3/2}) vs 1/T is a straight line of slope −Eg/(2k).',
    story: 'A pair costs Eg. ni is the geometric mean of the two carriers, so the exponent is Eg/2.',
    valid: 'Fixed-Eg teaching model. Homework anchors ni(300) from the table.',
    chain: 'Eg ↓ → ni ↑ → intrinsic regime at lower T → n ≈ ND dies sooner.',
    trap: 'ni does not double when T doubles. The 1/T exponential owns the story.',
    check: 'Why is the linearized slope −Eg/2k and not −Eg/k?',
    hw: 'HW2 Q5a–d.',
    module: 'latticelab_homeworks.html?hw=hw2&q=q5a',
  },
  e_sigma: {
    id: 'e_sigma', family: 'transport', name: 'Conductivity',
    latex: '\\sigma = q(n\\mu_n + p\\mu_p) = 1/\\rho',
    words: 'Two fluids of charge. Electrons contribute qnμn. Holes contribute qpμp. Add them.',
    vars: [
      { s: 'σ', m: 'conductivity', u: 'S/cm' },
      { s: 'μn, μp', m: 'mobilities', u: 'cm²/V·s' },
      { s: 'ρ', m: 'resistivity', u: 'Ω·cm' },
    ],
    cause: 'n or μn ↑ ⇒ σ ↑. Same field then gives more J. T is not written, but T moves n, p, and μ.',
    graph: 'J vs E is a line through the origin with slope σ (low field).',
    story: 'Jn = qnμnE, Jp = qpμpE. Factor E. That factor is σ.',
    valid: 'Low-field drift, uniform sample. Not velocity saturation.',
    chain: 'doping → n,p → σ → J = σE.',
    trap: 'Mobility is not concentration. Two samples with the same n can have different σ if μ differs.',
    check: 'Identical n, Sample A has 2× electron mobility. Who has larger σ, and why?',
    hw: 'HW2 Q3 σ column.',
    module: 'eqrel.html',
  },
  e_je: {
    id: 'e_je', family: 'transport', name: 'Local Ohm law',
    latex: 'J = \\sigma\\mathcal{E}',
    words: 'Current density increases when either conductivity or electric field increases.',
    vars: [
      { s: 'J', m: 'current density', u: 'A/cm²' },
      { s: 'E', m: 'electric field', u: 'V/cm' },
    ],
    cause: 'E doubles, σ fixed ⇒ J doubles. Linear, not exponential.',
    graph: 'Straight J–E line. Breakdown or saturation bends it.',
    story: 'Every microscopic drift piece is linear in E, so the total is linear in E.',
    valid: 'Ohmic, isotropic, steady drift. Not a reverse-biased diode’s exponential I–V.',
    chain: 'σ from carriers, then J = σE.',
    trap: 'Do not use J = σE as the Shockley diode law. A junction is not a resistor.',
    check: 'If E doubles and σ stays fixed, what happens to J?',
    hw: 'Transport family on the sheet. Wafer lab uses ρ, not this form.',
    module: 'eqrel.html',
  },
  e_vd: {
    id: 'e_vd', family: 'transport', name: 'Drift velocity',
    latex: 'v_d = \\mu\\mathcal{E}',
    words: 'A field tugs. Scattering stops runaway acceleration. The leftover average speed tracks the field.',
    vars: [
      { s: 'vd', m: 'drift velocity', u: 'cm/s' },
      { s: 'μ', m: 'mobility', u: 'cm²/V·s' },
    ],
    cause: 'Twice the field, twice the tug between collisions, twice the drift (low field).',
    graph: 'vd vs E is linear, then flattens at vsat.',
    story: 'm* dv/dt = qE − m*v/τ. Steady vd = (qτ/m*)E = μE.',
    valid: 'Low field, constant μ. Not ballistic short channels.',
    chain: 'μE → vd → J = qn vd.',
    trap: 'Carriers do not keep speeding up in a DC field. Scattering balances the tug.',
    check: 'E = 0. What is vd besides thermal jiggling?',
    hw: 'Sheet transport block.',
    module: 'eqrel.html',
  },
  e_mu: {
    id: 'e_mu', family: 'transport', name: 'Mobility',
    latex: '\\mu = q\\tau/m^*',
    words: 'Ease of motion. A long scattering time or a light effective mass makes a large mobility.',
    vars: [
      { s: 'τ', m: 'mean scattering time', u: 's' },
      { s: 'm*', m: 'effective mass', u: 'kg' },
    ],
    cause: 'τ ↑ or m* ↓ ⇒ μ ↑ ⇒ σ ↑ at fixed n.',
    graph: 'μ often falls as T or doping rises (more scattering). Course table quotes a 300 K number.',
    story: 'The lattice’s curvature became m*. The collision clock became τ. Their ratio is how hard the crystal is to push.',
    valid: 'Relaxation-time, low-field. Not a new rest mass.',
    chain: 'band curvature → m* → μ → σ.',
    trap: 'm* is a response, not a new particle mass. An electron at a band minimum can have vd = 0.',
    check: 'Sharper E(k) bend (larger |d²E/dk²|): larger or smaller |m*|?',
    hw: 'HW1 E–k intuition. Sheet mobility column.',
    module: 'index.html',
  },
  e_r: {
    id: 'e_r', family: 'transport', name: 'Bar resistance',
    latex: 'R = \\rho L/A',
    words: 'A longer bar or a skinnier cross-section makes a larger resistance. ρ is the material; L and A are geometry.',
    vars: [
      { s: 'R', m: 'resistance', u: 'Ω' },
      { s: 'L', m: 'length along current', u: 'cm' },
      { s: 'A', m: 'cross-sectional area', u: 'cm²' },
    ],
    cause: 'L ↑ ⇒ R ↑. A ↑ ⇒ R ↓. ρ ↑ ⇒ R ↑.',
    graph: 'R vs L is a line through the origin at fixed A.',
    story: 'V = EL and I = JA. Divide: R = V/I = (E/J)(L/A) = ρ L/A.',
    valid: 'Uniform bar, uniform current. Not a spreading contact or a junction.',
    chain: 'n,p → σ → ρ = 1/σ → R = ρL/A.',
    trap: 'Resistivity is not resistance. A short fat bar of high-ρ material can still have small R.',
    check: 'L doubles, A doubles. What happens to R?',
    hw: 'Sheet only. Four-point probe in the wafer lab measures ρ, not R.',
    module: 'wafer_lab.html',
  },
  e_poisson: {
    id: 'e_poisson', family: 'electrostatics', name: 'Poisson and the field',
    latex: '\\dfrac{d\\mathcal{E}}{dx}=\\dfrac{\\rho}{\\varepsilon_s\\varepsilon_0},\\quad \\mathcal{E}=-\\dfrac{dV}{dx}',
    words: 'Uncovered charge makes a field. The field’s slope is charge density over permittivity. Voltage is the downhill integral of that field.',
    vars: [
      { s: 'ρ', m: 'space-charge density', u: 'C/cm³' },
      { s: 'εs ε0', m: 'permittivity of the semiconductor', u: 'F/cm' },
    ],
    cause: 'More uncovered charge (heavier doping) ⇒ steeper E ⇒ larger |Emax| for a given width, and usually a narrower W.',
    graph: 'ρ rectangle → E triangle → V parabola. Bands follow −qV.',
    story: 'Gauss in one dimension. The same junction written as charge, then field, then potential, then bands.',
    valid: '1-D, electrostatics. Not a magnetic story.',
    chain: 'ρ → E → V → band bending.',
    trap: 'E is not “the voltage.” E is the slope of V.',
    check: 'If ρ is a rectangle, why is E a triangle?',
    hw: 'PN lab “four languages.” Exam 1 sheet electrostatics.',
    module: 'pn_lab.html?mode=lab',
  },
  e_rhoq: {
    id: 'e_rhoq', family: 'electrostatics', name: 'Space charge',
    latex: '\\rho = q(p-n+N_D^+-N_A^-)',
    words: 'Net charge is mobile holes and ionized donors minus mobile electrons and ionized acceptors.',
    vars: [
      { s: 'ND+', m: 'ionized donor density', u: 'cm^{-3}' },
      { s: 'NA−', m: 'ionized acceptor density', u: 'cm^{-3}' },
    ],
    cause: 'In depletion, n≈p≈0, so the P-side is ρ ≈ −qNA and the N-side is ρ ≈ +qND.',
    graph: 'Two opposite rectangles. Areas match: NA xp = ND xn.',
    story: 'Diffusion uncovers ions. Those ions are the space charge that builds the field until drift cancels diffusion.',
    valid: 'Complete ionization in the homework model. Bulk neutrality is the algebraic cousin n + NA = p + ND.',
    chain: 'doping → uncovered ions → ρ → E → Vbi.',
    trap: 'Neutrality is not n = p. Neutrality includes the impurity ions.',
    check: 'Why does the depletion region extend farther into the lighter-doped side?',
    hw: 'PN lab charge-balance panel.',
    module: 'pn_lab.html?mode=lab',
  },
  e_vbi: {
    id: 'e_vbi', family: 'pn', name: 'Built-in voltage',
    latex: 'V_{bi}=\\dfrac{kT}{q}\\ln\\!\\left(\\dfrac{N_A N_D}{n_i^2}\\right)',
    words: 'The barrier that makes EF flat. Heavier doping or a smaller ni (colder, wider gap) makes a larger Vbi.',
    vars: [
      { s: 'Vbi', m: 'built-in potential', u: 'V' },
      { s: 'NA, ND', m: 'doping', u: 'cm^{-3}' },
    ],
    cause: 'NA or ND ↑ ⇒ Vbi ↑ (log). T ↑ ⇒ ni ↑ fast, so Vbi usually falls.',
    graph: 'Barrier height on the band diagram is q(Vbi − VA).',
    story: 'EF on the P-side sits near Ev. EF on the N-side sits near Ec. One electrostatic potential must connect those two bulk pictures.',
    valid: 'Abrupt, nondegenerate, complete ionization. Not high injection.',
    chain: 'Vbi − VA is the voltage the depletion integrals must support.',
    trap: 'Vbi is not an applied battery. You do not “measure Vbi with a voltmeter” on an open diode the way students hope.',
    check: 'Both sides doped 10× heavier. Does Vbi rise a little (log) or 10×?',
    hw: 'PN lab live readout. Sheet PN block.',
    module: 'pn_lab.html?mode=lab',
  },
  e_w: {
    id: 'e_w', family: 'pn', name: 'Depletion pieces',
    latex: 'x_n=\\sqrt{\\dfrac{2\\varepsilon_s(V_{bi}-V_A)}{q}\\dfrac{N_A}{N_D(N_A+N_D)}},\\; W=x_n+x_p',
    words: 'The uncovered-ion slab must support Vbi−VA. More doping means you need less width to get the same charge. Forward bias shrinks the barrier and the width.',
    vars: [
      { s: 'xn, xp', m: 'N-side and P-side depletion', u: 'cm or μm' },
      { s: 'W', m: 'total depletion width', u: 'cm' },
      { s: 'VA', m: 'applied bias', u: 'V, + forward' },
    ],
    cause: 'Forward VA ↑ ⇒ (Vbi−VA) ↓ ⇒ W ↓. Reverse ⇒ W ↑. NA or ND ↑ ⇒ W generally ↓. Lighter-doped side takes more of W.',
    graph: 'W vs VA shrinks toward forward, grows as √|reverse| until punch-through (beyond this course).',
    story: 'NA xp = ND xn (area match). Poisson then fixes the scale of W from the potential drop.',
    valid: 'Abrupt, fully depleted, VA < Vbi. Not punch-through.',
    chain: 'forward bias ↑ → barrier ↓ → W ↓ → injection ↑ → I rises exponentially.',
    trap: 'Heavier doping does not “need a bigger field region.” It packs the same (or more) charge into a thinner slab.',
    check: 'ND ≫ NA. Which side contains most of W, and why?',
    hw: 'PN lab. HW-style exam intuition.',
    module: 'pn_lab.html?mode=lab',
  },
  e_shockley: {
    id: 'e_shockley', family: 'pn', name: 'Shockley diode',
    latex: 'I = I_0\\left(e^{qV_A/kT}-1\\right)',
    words: 'Forward: the barrier drops, a Boltzmann tail of majority carriers climbs it, current explodes. Reverse: that climb is shut; leftover current sits near −I0.',
    vars: [
      { s: 'I0', m: 'reverse saturation current', u: 'A' },
      { s: 'VA', m: 'applied voltage', u: 'V' },
    ],
    cause: 'VA ↑ (forward) ⇒ I rises exponentially. T ↑ ⇒ I0 rises hard because I0 tracks ni².',
    graph: 'Exponential forward, almost flat reverse on a linear I–V. Log I vs VA is a line of slope q/kT.',
    story: 'The exponential is a shrinking barrier dumping a Boltzmann tail, not a personality trait of the diode symbol.',
    valid: 'Ideal Shockley. Not series resistance, not breakdown, not high injection.',
    chain: 'VA ↑ → barrier ↓ → injection ↑ → I ↑.',
    trap: 'Reverse current is not “zero because nothing moves.” Drift of minorities still exists. It is just small.',
    check: 'Name the causal order: barrier, W, injection, current, when forward bias increases.',
    hw: 'PN lab I–V. Core Concepts diode tab.',
    module: 'pn_lab.html?mode=lab',
  },
  e_beer: {
    id: 'e_beer', family: 'optics', name: 'Beer attenuation',
    latex: 'I = I_0 e^{-\\alpha x},\\quad \\Delta I = I_0(1-e^{-\\alpha x})',
    words: 'Each slice of crystal eats a fixed fraction of the light that reaches it. That is an exponential, not a straight line.',
    vars: [
      { s: 'I', m: 'intensity remaining', u: 'arbitrary or W/cm²' },
      { s: 'α', m: 'absorption coefficient', u: 'cm^{-1}' },
      { s: 'x', m: 'depth', u: 'cm' },
      { s: 'ΔI', m: 'absorbed intensity', u: 'same as I' },
    ],
    cause: 'α ↑ or x ↑ ⇒ I falls faster. Doubling α does not halve I unless αx was already ln 2.',
    graph: 'I vs x is a decaying exponential. α(λ) is ~0 for λ > λg, then rises.',
    story: 'dI = −α I dx. Separate and integrate. The leftover is e^{−αx}. What was eaten is 1 − e^{−αx}.',
    valid: 'Uniform α, no multiple reflections (homework often forbids reflection).',
    chain: 'Ephoton vs Eg → α(λ) → I(x).',
    trap: 'Linear thinking: “α doubled so I halved.” Only true for a special αx.',
    check: 'α doubles, x fixed. Does transmitted intensity halve? Why not?',
    hw: 'Sheet optics. HW2 Q1 uses the onset of α, not a numerical Beer solve.',
    module: 'latticelab_homeworks.html?hw=hw2&q=q1a',
  },
  e_table: {
    id: 'e_table', family: 'table', name: 'Sheet table & constants',
    latex: 'hc=1240\\,\\mathrm{eV\\cdot nm},\\; k=8.62\\times10^{-5}\\,\\mathrm{eV/K}',
    words: 'The table is a set of material facts, not a menu of formulas. Eg, gap type, a, μ, m*, εs, and ni(300) are inputs to the equations above.',
    vars: [
      { s: 'Si', m: 'Eg 1.12 eV, indirect, a = 5.43 Å, ni(300) ~ 1×10^{10} cm^{-3}' },
      { s: 'Ge', m: 'Eg 0.66 eV, indirect, much larger ni' },
      { s: 'GaAs', m: 'Eg 1.42 eV, direct, small ni, huge μn' },
    ],
    cause: 'Smaller Eg ⇒ larger ni ⇒ intrinsic sooner. Direct ⇒ steep α and efficient band-edge emission.',
    graph: 'Rank materials by Eg or by ni. They run opposite.',
    story: 'Crystal structure sets a and N. Chemistry sets Eg and whether the CB minimum sits at the same k as the VB maximum.',
    valid: 'Room-temperature ballparks. Real LEDs also use alloys and wells.',
    chain: 'table Eg → λg, ni(T), optical color, Tmax.',
    trap: 'Si “cannot emit light” is too strong. Indirect emission is inefficient, not forbidden by a conservation-law brick wall in every device.',
    check: 'Rank Si, Ge, GaAs by expected ni(300) using only Eg and gap type as clues.',
    hw: 'HW2 materials. HW1 Si a = 5.431 Å, N = 8.',
    module: 'latticelab_homeworks.html?hw=hw2&q=q3i',
  },
};

export const SHEET_ORDER = [
  'e_hc', 'e_lg', 'e_f', 'e_n_nc', 'e_p_nv', 'e_n_ni', 'e_p_ni', 'e_np',
  'e_nc', 'e_nv', 'e_ni', 'e_sigma', 'e_je', 'e_vd', 'e_mu', 'e_r',
  'e_poisson', 'e_rhoq', 'e_vbi', 'e_w', 'e_shockley', 'e_beer', 'e_table',
];

export const CHAINS = [
  {
    id: 'eg-lg',
    title: 'Eg ↑ → absorption edge',
    start: 'Eg increases',
    steps: [
      'Photon energy needed to cross the gap rises.',
      'λg = hc/Eg therefore falls.',
      'The absorption edge moves to shorter wavelength.',
    ],
    hold: 'T, material family, hc',
  },
  {
    id: 't-fd',
    title: 'T ↑ → Fermi–Dirac',
    start: 'Temperature increases',
    steps: [
      'kT grows, so (E−EF)/kT shrinks at a fixed E.',
      'The 1→0 drop smears over more energy.',
      'f(EF) stays 1/2. Occupation above EF increases a little; below EF decreases a little.',
    ],
    hold: 'EF (for this isolated statement)',
  },
  {
    id: 'nd-n',
    title: 'ND ↑ → n, p, σ',
    start: 'Donor density increases (extrinsic, ionized)',
    steps: [
      'EF is pulled toward Ec.',
      'n rises (n ≈ ND on the checklist).',
      'p = ni²/n falls.',
      'σ ≈ q n μn rises if μn is not destroyed by extra scattering.',
    ],
    hold: 'T, NA ≈ 0, complete ionization',
  },
  {
    id: 'na-p',
    title: 'NA ↑ → p, n',
    start: 'Acceptor density increases',
    steps: [
      'EF is pulled toward Ev.',
      'p rises.',
      'n falls through mass action.',
    ],
    hold: 'T, ND ≈ 0, ionized',
  },
  {
    id: 'mu-j',
    title: 'μ ↑ → J at fixed E',
    start: 'Electron mobility increases',
    steps: [
      'Carriers drift faster at the same field.',
      'σ = q(nμn+pμp) rises.',
      'J = σE rises.',
    ],
    hold: 'n, p, E',
  },
  {
    id: 'r-geom',
    title: 'Geometry → R',
    start: 'L increases or A decreases',
    steps: [
      'Same ρ, longer path or skinnier pipe.',
      'R = ρL/A rises.',
    ],
    hold: 'ρ',
  },
  {
    id: 'alpha-i',
    title: 'α ↑ → transmitted I',
    start: 'Absorption coefficient increases',
    steps: [
      'Each dx eats a larger fraction of the remaining intensity.',
      'I = I0 e^{−αx} falls faster. Not a linear half.',
    ],
    hold: 'x, I0',
  },
  {
    id: 'fwd',
    title: 'Forward bias',
    start: 'Forward VA increases',
    steps: [
      'Barrier q(Vbi−VA) drops.',
      'Depletion width shrinks.',
      'Majority injection rises.',
      'Diode current rises exponentially.',
    ],
    hold: 'NA, ND, T (to first order on this chain)',
  },
  {
    id: 'rev',
    title: 'Reverse bias',
    start: 'Reverse |VA| increases',
    steps: [
      'Barrier rises.',
      'W grows.',
      'Majority diffusion over the barrier is suppressed.',
      'Current sits near −I0 until breakdown (not on Exam 1 arithmetic).',
    ],
    hold: 'doping',
  },
  {
    id: 'dop-w',
    title: 'Doping → W',
    start: 'NA or ND increases',
    steps: [
      'More uncovered charge per length.',
      'The same potential drop needs less width.',
      'W generally falls. The lighter-doped side still owns more of W.',
    ],
    hold: 'VA, T',
  },
  {
    id: 'eg-t',
    title: 'Eg ↓ → intrinsic earlier',
    start: 'Bandgap decreases',
    steps: [
      'ni ∝ exp(−Eg/2kT) grows strongly.',
      'ni overtakes ND or NA at a lower T.',
      'The extrinsic plateau ends sooner.',
    ],
    hold: 'ND, NA',
  },
];

export function sheetEq(id) {
  return SHEET[id];
}
