export const TRAPS = [
  {
    id: 't-ek-height', cat: 'band',
    claim: 'An electron at the top of an E–k diagram is physically higher in the crystal.',
    answer: false,
    why: 'The vertical axis is energy of a Bloch state, not height in the chip. k is crystal momentum, not a street address.',
    model: 'E–k is a map of allowed states. Real-space position is a different plot.',
    eq: 'E(k)', hw: 'HW1 Q4', module: 'latticelab_homeworks.html?hw=hw1#ek',
  },
  {
    id: 't-ef-avg', cat: 'fermi',
    claim: 'EF is the average electron energy.',
    answer: false,
    why: 'EF is the energy that centers f(E). Most electrons still sit in the valence band. f(EF)=1/2 is a definition check, not a population average.',
    model: 'EF is a chemical-potential-like dial. Occupation = DOS × f, not “everyone lives at EF.”',
    eq: 'f(E)', hw: 'HW1 Q5', module: 'latticelab_homeworks.html?hw=hw1#fermi',
  },
  {
    id: 't-f-half', cat: 'fermi',
    claim: 'f(E)=0.5 means half an electron exists at EF.',
    answer: false,
    why: 'f is a probability that an available state is occupied. Number = available states × f. At EF that probability is 1/2 for any T > 0.',
    model: 'Probability, not a fractional particle.',
    eq: 'f(E)=1/[1+exp((E−EF)/kT)]', hw: 'HW1 Q5', module: 'latticelab_homeworks.html?hw=hw1#fermi',
  },
  {
    id: 't-donor-always', cat: 'doping',
    claim: 'Adding donors adds electrons directly to the conduction band regardless of temperature.',
    answer: false,
    why: 'A donor electron is bound until thermal energy ionizes it. At T = 0, or when EI > 3kT, those electrons are frozen on the impurity. HW2 Q4(i) is the 0 K picture.',
    model: 'Temperature → kT → ionization → then n ≈ ND.',
    eq: '3kT ionization rule', hw: 'HW2 Q2, Q4(i)', module: 'latticelab_homeworks.html?hw=hw2&q=q4i',
  },
  {
    id: 't-n-density', cat: 'crystal',
    claim: 'More atoms per unit cell always means a material has greater mass density.',
    answer: false,
    why: 'Mass density is (N × molar mass) / (NA × a³). A large conventional cell (large a) can more than cancel a larger N. Diamond Si has N=8, but a is 5.43 Å, not “more packed than FCC aluminum” by N alone.',
    model: 'Compare N and a together. Never N by itself.',
    eq: 'n = N/a³', hw: 'HW1 Q1, Q3', module: 'latticelab_homeworks.html?hw=hw1#ek',
  },
  {
    id: 't-below-gap', cat: 'photon',
    claim: 'A photon with energy below Eg is absorbed but just produces less energetic carriers.',
    answer: false,
    why: 'Below Eg there is no allowed pair of band states to jump between (teaching model). The photon is not absorbed across the gap. α stays ~0 for λ > λg.',
    model: 'Ephoton ≥ Eg is a ticket. Cheaper tickets are not “smaller electrons.”',
    eq: 'E = hc/λ, λg = hc/Eg', hw: 'HW2 Q1', module: 'latticelab_homeworks.html?hw=hw2&q=q1a',
  },
  {
    id: 't-indirect-dark', cat: 'band',
    claim: 'An indirect semiconductor cannot absorb light.',
    answer: false,
    why: 'It can. A phonon supplies the missing Δk. Absorption is weaker and α rises slowly, but Si still has an absorption edge near 1.12 eV. Emission is inefficient, not forbidden by a brick wall.',
    model: 'Photon: almost vertical. Phonon: almost horizontal. Both together on Si.',
    eq: 'energy and crystal-momentum conservation', hw: 'HW1 Q4', module: 'latticelab_homeworks.html?hw=hw1#ek',
  },
  {
    id: 't-heat-sigma', cat: 'temperature',
    claim: 'Heating always decreases semiconductor conductivity.',
    answer: false,
    why: 'Metals often lose μ as T rises. A semiconductor can gain enormous n and p from ni(T). In the intrinsic regime σ usually rises with T. In freeze-out, heating ionizes dopants and σ rises. Only on a pure-scattering story would μ’s fall own σ.',
    model: 'Name the regime first. Then decide whether n(T) or μ(T) wins.',
    eq: 'σ = q(nμn+pμp), ni(T)', hw: 'HW2 Q5', module: 'latticelab_homeworks.html?hw=hw2&q=q5b',
  },
  {
    id: 't-hole-particle', cat: 'carriers',
    claim: 'A hole is a positively charged physical particle inserted into the lattice.',
    answer: false,
    why: 'A hole is a missing valence electron. The remaining sea shifting against the field is equivalent to a +q particle drifting with the field. Doping does not drop tiny plus balls into the crystal.',
    model: 'Empty valence state → +q behavior.',
    eq: 'p = NV exp(−(EF−Ev)/kT)', hw: 'HW2 Q2a, Q3', module: 'eqrel.html',
  },
  {
    id: 't-nd-ntype', cat: 'doping',
    claim: 'If ND is nonzero, the material must be n-type.',
    answer: false,
    why: 'Compensation: if NA > ND the net is p-type. If both are ≪ ni the crystal is intrinsic. HW2 Q3(i) is NA = 10 cm^{-3} in Si — that is not p-type ownership.',
    model: 'Compare NA, ND, and ni. Then name the type.',
    eq: 'n + NA = p + ND', hw: 'HW2 Q3', module: 'latticelab_homeworks.html?hw=hw2&q=q3i',
  },
  {
    id: 't-highT-dop', cat: 'temperature',
    claim: 'At high enough temperature, dopant concentration always determines carrier concentration.',
    answer: false,
    why: 'That is the extrinsic plateau. At still higher T, ni(T) overtakes ND or NA and pair generation owns n and p. HW2 Q5d is the device-failure version of that sentence.',
    model: 'Freeze-out → extrinsic → intrinsic.',
    eq: 'ni ∝ T^{3/2} exp(−Eg/2kT)', hw: 'HW2 Q5b–d', module: 'latticelab_homeworks.html?hw=hw2&q=q5d',
  },
  {
    id: 't-miller-neg', cat: 'miller',
    claim: 'A negative Miller index means the plane has a negative size.',
    answer: false,
    why: 'A barred index means the intercept on that axis is on the negative side of the origin (or the direction component points backward). Lengths stay positive. We often shift the drawing by one lattice step so the plane still cuts the conventional cell.',
    model: '(1-10) is a real plane. It is not “negative area.”',
    eq: 'intercepts a/h, b/k, c/l', hw: 'HW1 Q2', module: 'latticelab_homeworks.html?hw=hw1#miller',
  },
  {
    id: 't-miller-zero', cat: 'miller',
    claim: 'Index 0 means the plane intersects that axis at zero.',
    answer: false,
    why: 'Index 0 means the intercept is at infinity: the plane is parallel to that axis and never hits it. (110) is parallel to z, so l = 0.',
    model: '0 ⇒ parallel. Reciprocal of infinity is zero.',
    eq: '(hkl)', hw: 'HW1 Q2', module: 'latticelab_homeworks.html?hw=hw1#miller',
  },
  {
    id: 't-si-led', cat: 'photon',
    claim: 'Si cannot emit light because it has an indirect bandgap.',
    answer: false,
    why: 'Indirect emission needs a phonon and is inefficient. That is why we do not make good Si LEDs. It is not a conservation-law ban on every photon in silicon. Absorption still happens with phonon help.',
    model: 'Inefficient ≠ impossible. HW1 asks you to conserve E and k, not to declare Si dark forever.',
    eq: 'vertical photon, horizontal phonon', hw: 'HW1 Q4', module: 'latticelab_homeworks.html?hw=hw1#ek',
  },
  {
    id: 't-hot-bright', cat: 'doping',
    claim: 'Higher temperature always makes an LED brighter.',
    answer: false,
    why: 'HW2 CdS is a special ionization story: 400 K covers a 90 meV acceptor, 300 K does not. Heat can also increase nonradiative paths. Never collapse to “hotter = brighter.”',
    model: 'T → kT → ionization/trap → carriers → recombination.',
    eq: 'EI ≤ 3kT', hw: 'HW2 Q2b', module: 'latticelab_homeworks.html?hw=hw2&q=q2bii',
  },
  {
    id: 't-emit-in', cat: 'photon',
    claim: 'If a 470 nm laser is absorbed, the crystal must emit 470 nm.',
    answer: false,
    why: 'The electron relaxes to the band edge. Emission is near λg = hc/Eg. CdSe absorbs 470 nm and emits ~713 nm red.',
    model: 'Input ticket vs gap as the way out.',
    eq: 'λemit ≈ 1240/Eg', hw: 'HW2 Q1c', module: 'latticelab_homeworks.html?hw=hw2&q=q1c',
  },
  {
    id: 't-linear-alpha', cat: 'optics',
    claim: 'If α doubles and x is fixed, transmitted intensity halves.',
    answer: false,
    why: 'I = I0 e^{−αx}. Doubling α squares the remaining fraction: e^{−2αx} = (e^{−αx})². That equals 1/2 only for a special αx = ln√2.',
    model: 'Exponential, not a pie chart.',
    eq: 'I = I0 exp(−αx)', hw: 'Equation sheet optics', module: 'exam1.html?mode=sheet&eq=e_beer',
  },
  {
    id: 't-both-majority', cat: 'carriers',
    claim: 'In a doped semiconductor at equilibrium you may take n = ND and p = NA at the same time.',
    answer: false,
    why: 'Those two shortcuts describe opposite crystals. One sample has one majority. The minority is ni² over the majority.',
    model: 'Name the type, then mass action.',
    eq: 'np = ni²', hw: 'HW2 Q3', module: 'latticelab_homeworks.html?hw=hw2&q=q3ii',
  },
  {
    id: 't-new-band', cat: 'doping',
    claim: 'Doping creates a new conduction band.',
    answer: false,
    why: 'Doping adds impurity levels and shifts EF. Ec and Ev stay the host bands. You did not invent a second silicon.',
    model: 'Same gap, new EF, maybe a dash in the gap.',
    eq: 'band diagram + impurity level', hw: 'HW2 Q2, Q4', module: 'latticelab_homeworks.html?hw=hw2&q=q2a',
  },
  {
    id: 't-w-doping', cat: 'pn',
    claim: 'Heavier doping makes a wider depletion region because there is more charge to uncover.',
    answer: false,
    why: 'More charge per length means you need less length to support the same potential. W generally shrinks as NA or ND rises. The lighter side still takes more of W.',
    model: 'NA xp = ND xn, and Poisson sets the scale.',
    eq: 'W(NA, ND, Vbi−VA)', hw: 'PN lab', module: 'pn_lab.html?mode=lab',
  },
];
